<?php
$imageTeaserData = $block->getImageTeaserData();
$slide = $block->getSlide();
$contrastOptimizers = $slide->getOptimizers();
$contrastOptimizersScenarios = $contrastOptimizers['scenarios'];
$container = $contrastOptimizersScenarios['container'] ?? null;
?>
<?php if (isset($container['enabled']) && $container['enabled']): ?>
    <div class="cs-image-teaser__optimizer-container" style="opacity: <?= ((int)$container['intensity']) / 100 ?>"></div>
<?php endif; ?>
