<?php
/**
 * Call to action properties.
 */
$imageTeaserData = $block->getImageTeaserData();
$slide = $block->getSlide();
$cta = $slide->getCta();
$ctaHref = $cta['href'] ?? '';
$ctaLabel = $cta['label'] ?? '';
?>
<?php if ($ctaHref and $ctaLabel): ?>
    <div class="cs-image-teaser__cta">
        <span role="button"
            class="cs-image-teaser__cta-button">
            <span class="cs-image-teaser__cta-button-span"><?= $ctaLabel ?></span>
            <?= $this->getLayout()
                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                ->setIconUrl($block->getVar('image_teaser/cta_button_icon_path', 'MageSuite_ContentConstructorFrontend'))
                ->setCssClass('cs-image-teaser__cta-button-icon')
                ->setInlined(true)
                ->toHtml(); 
            ?>
        </span>
    </div>
<?php endif; ?>
