<?php
/**
 * Call to action properties.
 */
$imageTeaserData = $block->getImageTeaserData();
$slide = $block->getSlide();
$cta = $slide->getCta();
$ctaHref = $cta['href'] ?? '';
$ctaLabel = $cta['label'] ?? '';
$iconPath = $block->getVar('image_teaser/cta_button_icon_path', 'MageSuite_ContentConstructorFrontend');
?>
<?php if ($ctaHref and $ctaLabel): ?>
    <div class="cs-image-teaser__cta">
        <span class="cs-image-teaser__cta-span"><?= $ctaLabel ?></span>
        <?php if(!empty($iconPath)): ?>
            <?= $this->getLayout()
                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                ->setIconUrl($iconPath)
                ->setCssClass('cs-image-teaser__cta-icon')
                ->setInlined(true)
                ->toHtml();
            ?>
        <?php endif ?>
    </div>
<?php endif; ?>
