<?php
$imageTeaserData = $block->getImageTeaserData();
$imageTypeHelper = $this->helper(\MageSuite\ThemeHelpers\Helper\ImageType::class);
$slide = $block->getSlide();
$isSvg = $slide->isSvg();

/**
 * Image properties with support for conditional lazy loading.
 */

$origImageSrc = $block->escapeUrl($slide->getSrc());
$hasImage = !empty($origImageSrc);
$imageSrcset = $slide->getSrcSet();

if (empty($imageSrcset) || $isSvg) {
    $imageSrcset = $origImageSrc;
}

$imageAlt = $block->escapeHtmlAttr($slide->getAlt());
$imageSizes = $isSvg ? '' : $slide->getSizes();
$isSlider = $block->getIsSlider();
$isSliderMobile = $block->getIsSliderMobile();

/**
 * Aspect ratio and sizing
 */
$aspectRatio = $block->getAspectRatio();
$imageWidth = $slide->getWidth();
$imageHeight = $slide->getHeight();

/**
 * Contrast optimizers
 */
$contrastOptimizers = $slide->getOptimizers();
$mirrorImage = $contrastOptimizers['mirror_image'] ?? null;

/**
 * WebP support
 */
$isWebpSupported = $imageTypeHelper->supportsWebp($origImageSrc);
$imageMimeType = $imageTypeHelper->getMimeType($origImageSrc);
if ($isWebpSupported) {
    $imageWebpSrcSet = $slide->getWebpSrcSet();
}
?>
<?php if ($hasImage): ?>
    <picture class="cs-image-teaser__picture"<?php if($aspectRatio): ?> style="aspect-ratio: <?= $aspectRatio ?>"<?php endif ?>>
        <?php if ($isWebpSupported): ?>
            <source
                type="image/webp"
                srcset="<?= $imageWebpSrcSet ?>"
                <?php if ($imageSizes): ?>
                    sizes="<?= $imageSizes ?>"
                <?php endif; ?>
                <?php if ($imageWidth): ?>
                    width="<?= $imageWidth ?>"
                <?php endif; ?>
                <?php if ($imageHeight): ?>
                    height="<?= $imageHeight ?>"
                <?php endif; ?>
            >
        <?php endif; ?>
        <source
            type="<?= $imageMimeType ?>"
            srcset="<?= $imageSrcset ?>"
            <?php if ($imageSizes): ?>
                sizes="<?= $imageSizes ?>"
            <?php endif; ?>
            <?php if ($imageWidth): ?>
                width="<?= $imageWidth ?>"
            <?php endif; ?>
            <?php if ($imageHeight): ?>
                height="<?= $imageHeight ?>"
            <?php endif; ?>
        >
        <img
            class="cs-image-teaser__image<?= $mirrorImage ? ' cs-image-teaser__image--mirror' : '' ?>"
            alt="<?= $imageAlt ?>"
            src="<?= $origImageSrc ?>"
            loading="lazy"
            <?php if ($imageSizes): ?>
                sizes="<?= $imageSizes ?>"
            <?php endif; ?>
            <?php if ($imageWidth): ?>
                width="<?= $imageWidth ?>"
            <?php endif; ?>
            <?php if ($imageHeight): ?>
                height="<?= $imageHeight ?>"
            <?php endif; ?>
        >
    </picture>
<?php endif; ?>
