<?php

namespace MageSuite\ContentConstructorFrontend\DataProviders\ComponentsList;

abstract class HeroCarousel implements DataProviderBlocksInterface
{
    protected $mobileDisplayVariant = '';
    protected $subtitle = '';
    
    public function getBlocks(){
        $blocks = [];
        $blocks[] = Index::getHeadlineBlock('Hero Carousel scenarios', $this->subtitle);

        $blocks['componentea06'] = [
            'id' => 'componentea06',
            'section' => 'content',
            'type' => 'hero-carousel',
            'data' => [
                'mobileDisplayVariant' => $this->mobileDisplayVariant,
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-1',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Test subheadline',
                        'paragraph' => 'Test paragraph',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                        'ctaLabel' => 'Dark',
                        'href' => 'http://www.creativestyle.pl/'

                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-2',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Test subheadline',
                        'paragraph' => 'Test paragraph',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                        'ctaLabel' => 'Dark',
                        'href' => 'http://www.creativestyle.pl/'
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-3',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Test subheadline',
                        'paragraph' => 'Test paragraph',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                        'ctaLabel' => 'Dark',
                        'href' => 'http://www.creativestyle.pl/'
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-4',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Test subheadline',
                        'paragraph' => 'Test paragraph',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                        'ctaLabel' => 'Dark',
                        'href' => 'http://www.creativestyle.pl/'
                    ],
                ],
            ],
        ];

        $blocks[] = [
            'id' => 'componentcceb',
            'section' => 'content',
            'type' => 'hero-carousel',
            'data' => [
                'mobileDisplayVariant' => $this->mobileDisplayVariant,
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-1',
                        'colorScheme' => 'light',
                        'headline' => 'Test headline',
                        'subheadline' => 'Test subheadline',
                        'paragraph' => 'Text vertically centered on the left ',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                        'ctaLabel' => 'Light',
                        'href' => 'http://www.creativestyle.pl/'
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-2',
                        'colorScheme' => 'light',
                        'headline' => 'Test headline',
                        'subheadline' => 'Test subheadline',
                        'paragraph' => 'Text on the bottom, left corner',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                        'ctaLabel' => 'Light',
                        'href' => 'http://www.creativestyle.pl/'
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-3',
                        'colorScheme' => 'light',
                        'headline' => 'Test headline',
                        'subheadline' => 'Test subheadline',
                        'paragraph' => 'Text vertically centered in the middle',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                        'ctaLabel' => 'Light',
                        'href' => 'http://www.creativestyle.pl/'
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-4',
                        'colorScheme' => 'light',
                        'headline' => 'Test headline',
                        'subheadline' => 'Test subheadline',
                        'paragraph' => 'Text on the bottom, centered',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                        'ctaLabel' => 'Light',
                        'href' => 'http://www.creativestyle.pl/'
                    ],
                ],
            ],
        ];

        $blocks[] = [
            'id' => 'componentf13e',
            'section' => 'content',
            'type' => 'hero-carousel',
            'data' => [
                'mobileDisplayVariant' => $this->mobileDisplayVariant,
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-1',
                        'colorScheme' => 'light',
                        'headline' => '',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-1',
                        'colorScheme' => 'light',
                        'headline' => '',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-1',
                        'colorScheme' => 'light',
                        'headline' => '',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-1',
                        'colorScheme' => 'light',
                        'headline' => '',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                ],
            ],
        ];

        $blocks[] = [
            'id' => 'component77be',
            'section' => 'content',
            'type' => 'hero-carousel',
            'data' => [
                'mobileDisplayVariant' => $this->mobileDisplayVariant,
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline only',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-2',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline only',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-3',
                        'colorScheme' => 'light',
                        'headline' => 'Headline only',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-4',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline only',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Subheadline',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-2',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Subheadline',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-3',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Subheadline',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-4',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Subheadline',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    8 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-2',
                        'colorScheme' => 'dark',
                        'headline' => '',
                        'subheadline' => '',
                        'paragraph' => 'Only really long paragraph here. Only really long paragraph here. Only really long paragraph here. Only really long paragraph here. Only really long paragraph here. Only really long paragraph here. ',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    9 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-2',
                        'colorScheme' => 'light',
                        'headline' => '',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => 'Button only',
                        'href' => 'http://www.creativestyle.pl/',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                    ],
                    10 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-4',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Subheadline',
                        'paragraph' => '',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    11 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvcGx1c2gtZGVzaWduLXN0dWRpby01NTMzMTktdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/plush-design-studio-553319-unsplash.jpg"}}',
                        'displayVariant' => 'variant-2',
                        'colorScheme' => 'dark',
                        'headline' => '',
                        'subheadline' => '',
                        'paragraph' => 'Only really long paragraph here. Only really long paragraph here. Only really long paragraph here. Only really long paragraph here. Only really long paragraph here. Only really long paragraph here. ',
                        'ctaLabel' => '',
                        'href' => '',
                        'sizeInfo' => '1163x780px (1163:780)',
                        'aspectRatio' => '1163:780',
                    ],
                    12 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaGVucnktYXNjcm9mdC0xMTU0MTA1LXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/henry-ascroft-1154105-unsplash.jpg"}}',
                        'displayVariant' => 'variant-2',
                        'colorScheme' => 'light',
                        'headline' => '',
                        'subheadline' => '',
                        'paragraph' => '',
                        'ctaLabel' => 'Button only',
                        'href' => 'http://www.creativestyle.pl/',
                        'sizeInfo' => '1166x780px (583:390)',
                        'aspectRatio' => '583:390',
                    ],
                ],
            ],
        ];

        return $blocks;
    }
}
