<?php

namespace MageSuite\ContentConstructorFrontend\DataProviders\ComponentsList;

class ITContentWidthSlider implements DataProviderBlocksInterface
{
    public function getBlocks()
    {
        $blocks = [];
        $blocks[] = Index::getHeadlineBlock('Image Teasers for Content Width Slider');

        $blocks[] = Index::getHeadlineBlock('1 in row');
        $blocks[] = [
            'id' => 'componentc0f3',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvamFuLWxvc2VydC02MzM5NjAtdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/jan-losert-633960-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvamFuLWxvc2VydC02MzM5NjAtdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/jan-losert-633960-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'light',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'light',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'light',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '1 in row',
                        'iconId' => 'dl_1',
                        'disabled' => '',
                        'teasersNum' => '1',
                        'id' => '1',
                    ],
                    'textPositioning' => [
                        'name' => 'Text over image',
                        'iconId' => 'tl_over',
                        'disabled' => '',
                        'textPosition' => '1',
                        'id' => 'over',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = Index::getHeadlineBlock('2 in row');
        $blocks[] = [
            'id' => 'componentbd0a',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'light',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'light',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'light',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '2 in row',
                        'iconId' => 'dl_2',
                        'disabled' => '',
                        'teasersNum' => '2',
                        'id' => '2',
                    ],
                    'textPositioning' => [
                        'name' => 'Text over image',
                        'iconId' => 'tl_over',
                        'disabled' => '',
                        'textPosition' => '1',
                        'id' => 'over',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = [
            'id' => 'component6397',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '2 in row',
                        'iconId' => 'dl_2',
                        'disabled' => '',
                        'teasersNum' => '2',
                        'id' => '2',
                    ],
                    'textPositioning' => [
                        'name' => 'Text below image',
                        'iconId' => 'tl_under',
                        'disabled' => '',
                        'textPosition' => '',
                        'id' => 'under',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = Index::getHeadlineBlock('3 in row');
        $blocks[] = [
            'id' => 'componentda0b',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'light',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'light',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'light',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '3 in row',
                        'iconId' => 'dl_3',
                        'disabled' => '',
                        'teasersNum' => '3',
                        'id' => '3',
                    ],
                    'textPositioning' => [
                        'name' => 'Text over image',
                        'iconId' => 'tl_over',
                        'disabled' => '',
                        'textPosition' => '1',
                        'id' => 'over',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = [
            'id' => 'componenta50e',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvamFuLWxvc2VydC02MzM5NjAtdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/jan-losert-633960-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '3 in row',
                        'iconId' => 'dl_3',
                        'disabled' => '',
                        'teasersNum' => '3',
                        'id' => '3',
                    ],
                    'textPositioning' => [
                        'name' => 'Text below image',
                        'iconId' => 'tl_under',
                        'disabled' => '',
                        'textPosition' => '',
                        'id' => 'under',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = Index::getHeadlineBlock('4 in row');
        $blocks[] = [
            'id' => 'component0335',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZXN0ZWUtamFuc3NlbnMtNzQ1ODYxLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/estee-janssens-745861-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'dark',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '573x571px (573:571)',
                        'aspectRatio' => '573:571',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'dark',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZXN0ZWUtamFuc3NlbnMtNzQ1ODYxLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/estee-janssens-745861-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'light',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'light',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'light',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '4 in row',
                        'iconId' => 'dl_4',
                        'disabled' => '',
                        'teasersNum' => '4',
                        'id' => '4',
                    ],
                    'textPositioning' => [
                        'name' => 'Text over image',
                        'iconId' => 'tl_over',
                        'disabled' => '',
                        'textPosition' => '1',
                        'id' => 'over',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = [
            'id' => 'component6e4c',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZXN0ZWUtamFuc3NlbnMtNzQ1ODYxLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/estee-janssens-745861-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '573x571px (573:571)',
                        'aspectRatio' => '573:571',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZXN0ZWUtamFuc3NlbnMtNzQ1ODYxLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/estee-janssens-745861-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '573x571px (573:571)',
                        'aspectRatio' => '573:571',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '4 in row',
                        'iconId' => 'dl_4',
                        'disabled' => '',
                        'teasersNum' => '4',
                        'id' => '4',
                    ],
                    'textPositioning' => [
                        'name' => 'Text below image',
                        'iconId' => 'tl_under',
                        'disabled' => '',
                        'textPosition' => '',
                        'id' => 'under',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = Index::getHeadlineBlock('6 in row');
        $blocks[] = [
            'id' => 'component5e9f',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMS5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/1.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMi5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/2.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNi5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/6.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNS5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/5.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNC5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/4.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMy5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/3.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMS5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/1.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMi5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/2.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    8 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNi5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/6.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    9 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNS5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/5.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    10 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNC5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/4.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    11 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMy5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/3.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '6 in row',
                        'iconId' => 'dl_6',
                        'disabled' => '',
                        'teasersNum' => '6',
                        'id' => '6',
                    ],
                    'textPositioning' => [
                        'name' => 'Text below image',
                        'iconId' => 'tl_under',
                        'disabled' => '',
                        'textPosition' => '',
                        'id' => 'under',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = Index::getHeadlineBlock('8 in row');
        $blocks[] = [
            'id' => 'component3aed',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMS5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/1.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMi5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/2.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNS5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/5.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNi5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/6.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNC5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/4.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMy5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/3.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMS5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/1.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'dark',
                        'headline' => 'Headline',
                        'subheadline' => 'Dark',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMi5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/2.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    8 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNi5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/6.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    9 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNS5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/5.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    10 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvNC5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/4.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                    11 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9Ind5c2l3eWcvMy5wbmcifX0',
                        'decodedImage' => '{{media url="creative_components/3.png"}}',
                        'displayVariant' => '1',
                        'colorScheme' => 'light',
                        'headline' => 'Headline',
                        'subheadline' => 'Light',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '195x90px (13:6)',
                        'aspectRatio' => '13:6',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Content width Slider',
                        'iconId' => 'tw_content-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'c-s',
                    ],
                    'desktopLayout' => [
                        'name' => '8 in row',
                        'iconId' => 'dl_8',
                        'disabled' => '',
                        'teasersNum' => '8',
                        'id' => '8',
                    ],
                    'textPositioning' => [
                        'name' => 'Text below image',
                        'iconId' => 'tl_under',
                        'disabled' => '',
                        'textPosition' => '',
                        'id' => 'under',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];
        
        return $blocks;
    }
}
