<?php

namespace MageSuite\ContentConstructorFrontend\DataProviders\ComponentsList;

class ITWindowWidthSlider implements DataProviderBlocksInterface
{
    public function getBlocks()
    {
        $blocks = [];
        $blocks[] = Index::getHeadlineBlock('Image teasers for window width slider');

        $blocks[] = Index::getHeadlineBlock('2 in row');
        $blocks[] = [
            'id' => 'component2967',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Window width Slider',
                        'iconId' => 'tw_window-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'w-s',
                    ],
                    'desktopLayout' => [
                        'name' => '2 in row',
                        'iconId' => 'dl_2',
                        'disabled' => '',
                        'teasersNum' => '2',
                        'id' => '2',
                    ],
                    'textPositioning' => [
                        'name' => 'Text over image',
                        'iconId' => 'tl_over',
                        'disabled' => '',
                        'textPosition' => '1',
                        'id' => 'over',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = [
            'id' => 'componentb51e',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Window width Slider',
                        'iconId' => 'tw_window-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'w-s',
                    ],
                    'desktopLayout' => [
                        'name' => '2 in row',
                        'iconId' => 'dl_2',
                        'disabled' => '',
                        'teasersNum' => '2',
                        'id' => '2',
                    ],
                    'textPositioning' => [
                        'name' => 'Text below image',
                        'iconId' => 'tl_under',
                        'disabled' => '',
                        'textPosition' => '',
                        'id' => 'under',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = Index::getHeadlineBlock('3 in row');
        $blocks[] = [
            'id' => 'component2269',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvamFuLWxvc2VydC02MzM5NjAtdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/jan-losert-633960-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvamFuLWxvc2VydC02MzM5NjAtdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/jan-losert-633960-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Window width Slider',
                        'iconId' => 'tw_window-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'w-s',
                    ],
                    'desktopLayout' => [
                        'name' => '3 in row',
                        'iconId' => 'dl_3',
                        'disabled' => '',
                        'teasersNum' => '3',
                        'id' => '3',
                    ],
                    'textPositioning' => [
                        'name' => 'Text over image',
                        'iconId' => 'tl_over',
                        'disabled' => '',
                        'textPosition' => '1',
                        'id' => 'over',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = [
            'id' => 'component9f4d',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvamFuLWxvc2VydC02MzM5NjAtdW5zcGxhc2guanBnIn19',
                        'decodedImage' => '{{media url="creative_components/jan-losert-633960-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'dark',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYW5uaWUtc3ByYXR0LTI5NDQ1MC11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/annie-spratt-294450-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZmVkZXJpY2EtZ2FsbGktNzAzNTcyLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/federica-galli-703572-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '1920x1022px (960:511)',
                        'aspectRatio' => '960:511',
                        'colorScheme' => 'light',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Window width Slider',
                        'iconId' => 'tw_window-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'w-s',
                    ],
                    'desktopLayout' => [
                        'name' => '3 in row',
                        'iconId' => 'dl_3',
                        'disabled' => '',
                        'teasersNum' => '3',
                        'id' => '3',
                    ],
                    'textPositioning' => [
                        'name' => 'Text below image',
                        'iconId' => 'tl_under',
                        'disabled' => '',
                        'textPosition' => '',
                        'id' => 'under',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        $blocks[] = Index::getHeadlineBlock('4 in row');
        $blocks[] = [
            'id' => 'component5cbc',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'dark',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'dark',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZXN0ZWUtamFuc3NlbnMtNzQ1ODYxLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/estee-janssens-745861-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'dark',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'dark',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Text vertically centered on the left',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'light',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Text on the bottom, left corner',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'light',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZXN0ZWUtamFuc3NlbnMtNzQ1ODYxLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/estee-janssens-745861-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Text vertically centered in the middle',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'light',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Text on the bottom - centered',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text over image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'light',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Window width Slider',
                        'iconId' => 'tw_window-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'w-s',
                    ],
                    'desktopLayout' => [
                        'name' => '4 in row',
                        'iconId' => 'dl_4',
                        'disabled' => '',
                        'teasersNum' => '4',
                        'id' => '4',
                    ],
                    'textPositioning' => [
                        'name' => 'Text over image',
                        'iconId' => 'tl_over',
                        'disabled' => '',
                        'textPosition' => '1',
                        'id' => 'over',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];
        
        $blocks[] = [
            'id' => 'component29af',
            'section' => 'content',
            'type' => 'image-teaser',
            'data' => [
                'items' => [
                    0 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'dark',
                    ],
                    1 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'dark',
                    ],
                    2 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZXN0ZWUtamFuc3NlbnMtNzQ1ODYxLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/estee-janssens-745861-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'dark',
                    ],
                    3 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Dark',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'dark',
                    ],
                    4 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '1',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'light',
                    ],
                    5 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvYWxleGFuZHJ1LWFjZWEtMTE2MDQ2MS11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/alexandru-acea-1160461-unsplash.jpg"}}',
                        'displayVariant' => '2',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'light',
                    ],
                    6 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvZXN0ZWUtamFuc3NlbnMtNzQ1ODYxLXVuc3BsYXNoLmpwZyJ9fQ==',
                        'decodedImage' => '{{media url="creative_components/estee-janssens-745861-unsplash.jpg"}}',
                        'displayVariant' => '3',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'light',
                    ],
                    7 => [
                        'image' => '/admin/content-constructor/image/show/image/e3ttZWRpYSB1cmw9ImNyZWF0aXZlX2NvbXBvbmVudHMvaG93YXJkLWxhd3JlbmNlLWItMTE0MTgxMy11bnNwbGFzaC5qcGcifX0=',
                        'decodedImage' => '{{media url="creative_components/howard-lawrence-b-1141813-unsplash.jpg"}}',
                        'displayVariant' => '4',
                        'headline' => 'Headline',
                        'subheadline' => 'Slider',
                        'paragraph' => 'Text below image',
                        'ctaLabel' => 'Light',
                        'href' => '{{widget type="Magento\\Cms\\Block\\Widget\\Page\\Link" template="widget/link/link_block.phtml" page_id="10001"}}',
                        'sizeInfo' => '574x571px (574:571)',
                        'aspectRatio' => '574:571',
                        'colorScheme' => 'light',
                    ],
                ],
                'ignoredItems' => [],
                'currentScenario' => [
                    'teaserWidth' => [
                        'name' => 'Window width Slider',
                        'iconId' => 'tw_window-slider',
                        'disabled' => '',
                        'teasersLimit' => '',
                        'id' => 'w-s',
                    ],
                    'desktopLayout' => [
                        'name' => '4 in row',
                        'iconId' => 'dl_4',
                        'disabled' => '',
                        'teasersNum' => '4',
                        'id' => '4',
                    ],
                    'textPositioning' => [
                        'name' => 'Text below image',
                        'iconId' => 'tl_under',
                        'disabled' => '',
                        'textPosition' => '',
                        'id' => 'under',
                    ],
                    'mobileLayout' => [
                        'name' => 'Slider',
                        'iconId' => 'ml_slider',
                        'disabled' => '',
                        'id' => 'slider',
                    ],
                ],
                'componentVisibility' => [
                    'mobile' => '1',
                    'desktop' => '1'
                ],
            ],
        ];

        return $blocks;
    }
}
