<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\BrandCarousel */
$componentConfiguration = $block->getData();

/** @var \MageSuite\ContentConstructorFrontend\Model\Component\BrandCarousel $viewModel */
$viewModel = $block->getViewModel();

$brands = $viewModel->getBrands();
?>
<section class="cs-container">
    <div class="cs-container__inner">
        <div class="<?=$block->getVisibilityClass()?>">
            <div class="cs-brand-carousel {{ mix }}">
                <div class="cs-brand-carousel__carousel">
                    <div class="cs-brand-carousel__wrapper">
                        <ul class="cs-brand-carousel__slides">

                            <?php foreach($brands as $brand): ?>
                            <li class="cs-brand-carousel__slide">
                                <?php if($brand['href']): ?>
                                <a href="<?=$brand['href']?>" class="cs-brand-carousel__slide-link">
                                <?php endif; ?>

                                    <?php if($brand['image']['src']): ?>
                                    <figure class="cs-brand-carousel__figure">
                                        <img
                                                class="cs-brand-carousel__image lazyload"
                                                src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
                                                data-src="<?=$brand['image']['src']?>"
                                                alt="<?=$brand['image']['alt']?>"
                                                <?php if(isset($brand['image']['width'])): ?>width="<?=$brand['image']['width']?>" <?php endif; ?>
                                                <?php if(isset($brand['image']['height'])): ?>height="<?=$brand['image']['height']?>" <?php endif; ?>
                                        >
                                        <noscript>
                                            <img
                                                    class="cs-brand-carousel__image"
                                                    src="<?=$brand['image']['src']?>"
                                                    alt="<?=$brand['image']['alt']?>"
                                                    <?php if(isset($brand['image']['width'])): ?>width="<?=$brand['image']['width']?>" <?php endif; ?>
                                                    <?php if(isset($brand['image']['height'])): ?>height="<?=$brand['image']['height']?>" <?php endif; ?>
                                            >
                                        </noscript>
                                    </figure>
                                    <?php endif; ?>
                                <?php if($brand['href']): ?>
                                </a>
                                <?php endif; ?>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>

                <button class="cs-brand-carousel__nav cs-brand-carousel__nav--prev"
                        type="button">
                    <svg class="cs-brand-carousel__nav-icon">
                        <use xlink:href="#icon_arrow-left"></use>
                    </svg>
                </button>
                <button class="cs-brand-carousel__nav cs-brand-carousel__nav--next"
                        type="button">
                    <svg class="cs-brand-carousel__nav-icon">
                        <use xlink:href="#icon_arrow-right"></use>
                    </svg>
                </button>

                <ul class="cs-brand-carousel__pagination "></ul>
            </div>
        </div>
    </div>
</section>
