<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\Button */
$componentConfiguration = $block->getData();
$visibilityClass = $this
    ->helper(\MageSuite\ContentConstructorFrontend\Helper\ComponentVisibility::class)
    ->getVisibilityClass($componentConfiguration);


$viewModel = $block->getViewModel();
?>

<div class="<?=$visibilityClass?>">
    <a href="<?=$viewModel->getHref()?>" class="cs-button cs-button--type_more-content">
        <?=$block->getLabel()?>

        <?php $numberOfProducts = $viewModel->getNumberOfProducts(); ?>
        <?php if(is_numeric($numberOfProducts)): ?>
        <span class="cs-button__span"><?=$numberOfProducts?></span>
        <?php endif; ?>

        <svg class="cs-button__icon">
            <use xlink:href="#arrow_next"></use>
        </svg>
    </a>
</div>
