<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\CategoryLinks */
/** @var \MageSuite\ContentConstructorFrontend\Model\Component\CategoryLinks $viewModel */
$viewModel = $block->getViewModel();
$categories = $viewModel->getCategories();
$subCategories = $categories['sub_categories'];
$shouldShowProductsCount = $viewModel->shouldShowProductsCount();
$visibility = $block->getVisibilityClass();
?>

<div <?php if (!empty($visibility)): ?> class="<?=$visibility?>" <?php endif; ?>>
    <div class="cs-container cs-container--category-links">
        <div class="cs-container__inner">
            <div class="cs-category-links <?php if(!$viewModel->hasSubcategories()): ?>cs-category-links--no-subcats <?php endif; ?><?= $block->getVar('category_links/additional_css_classes'); ?>" data-mage-init='{"collapsible":{"mediaQueryScope":"(max-width: 767px)"}}'>
            <?php if($block->getVar('category_links/show_title')): ?>
                <h2 class="cs-category-links__title"><?= $categories['main_category']['name'] ?></h2>
            <?php endif; ?>

                <div class="cs-category-links__dropdown cs-category-links-dropdown <?php if(!$viewModel->hasSubcategories()): ?> cs-category-links-dropdown--no-subcats <?php endif; ?>">
                    <?php
                    if($viewModel->hasSubcategories()): ?>
                    <div class="cs-category-links__subtitle | cs-category-links-dropdown__trigger" data-role="title">
                        <?=__('All Products')?> <?php if($shouldShowProductsCount): ?><span class="cs-category-links__qty"><?=$categories['main_category']['products_count']?></span><?php endif; ?>
                    </div>
                    <?php endif; ?>

                    <div class="cs-category-links__list-wrapper | cs-category-links-dropdown__content" data-role="content">
                        <?php if($viewModel->hasSubcategories()): ?>
                        <ul class="cs-category-links__list">
                            <?php $i = 1; ?>
                            <?php foreach($subCategories as $category): ?>
                            <li class="cs-category-links__list-item
                                <?php
                                    foreach($block->getVar('category_links/hide_links_breakpoints') as $breakpoint) {
                                        if($i >= (int)$breakpoint['hide_from']){echo $breakpoint['mix'] . ' ';}
                                    }
                                ?>"
                            >
                                <a href="<?=$category['url']?>" class="cs-category-links__link">
                                    <?=$category['name']?> <?php if($shouldShowProductsCount): ?><span class="cs-category-links__qty"><?=$category['products_count']?></span><?php endif; ?>
                                </a>
                            </li>
                            <?php $i++; ?>
                            <?php endforeach; ?>
                        </ul>
                        <?php endif; ?>

                        <ul class="cs-category-links__list-all">
                            <li class="cs-category-links__list-all-item">
                                <a href="<?=$categories['main_category']['url']?>" class="cs-category-links__link">
                                    <?php echo __($block->getVar('category_links/all_products/label')); ?> <?php if($shouldShowProductsCount): ?> <span class="cs-category-links__qty"><?=$categories['main_category']['products_count']?></span><?php endif; ?>
                                    <svg class="cs-category-links__list-all-icon">
                                        <use xlink:href="<?php echo $block->getVar('category_links/all_products/icon'); ?>"></use>
                                    </svg>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
