<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\CmsTeaser */
$componentConfiguration = $block->getData();

/** @var \MageSuite\ContentConstructorFrontend\Model\Component\CmsTeaser $viewModel */
$viewModel = $block->getViewModel();
$visibility = $block->getVisibilityClass();

$isSlider = false;
$isSliderMobile = false;

$itemsPerRow = $componentConfiguration['currentScenario']['desktopLayout']['id'];
$itemsPerRowMobile = 2;
$itemsPerViewMobile = 1;
$itemsPerView = $componentConfiguration['currentScenario']['desktopLayout']['id'];
$displayVariant = 'inside';

if ($componentConfiguration['currentScenario']['mobileLayout']['id'] == 'slider') {
    $itemsPerRowMobile = 1;
    $isSliderMobile = true;
}

$sizesMobile = '(max-width: 48em) 100vw';
$sizesDesktop = (100 / $itemsPerView) . 'vw';
$sizesDesktop = '(min-width: ' . $block->getVar('max_content_width') . 'px) ' . ($block->getVar('max_content_width') / $itemsPerView) . 'px, ' . $sizesDesktop;
$sizes = $sizesMobile . ', ' . $sizesDesktop;

$textDisplayVariant = $block->getData('textDisplayVariant') ?? 2;

$slides = $viewModel->getSlides();

foreach ($slides as $slide) {
    $slide->setData('displayVariant', $textDisplayVariant);
}

$componentClasses = ' cs-image-teaser--cms-pages';
$componentClasses .= $block->getSkipSpacing() ? ' cs-image-teaser--skip-spacing' : ''; 
$componentClasses .= ' ' . $block->getVar('cms_teaser/additional_css_classes');
?>

<div <?= $visibility ? 'class="' . $visibility . '"' : ''; ?>>
    <div class="cs-container cs-container--cms-teaser">
        <div class="cs-container__inner">
            <div class="cs-image-teaser
             cs-image-teaser--items-in-row-<?= $itemsPerRow ?>
             cs-image-teaser--items-in-row-mobile-<?= $itemsPerViewMobile ?>
             <?= $isSlider ? 'cs-image-teaser--slider' : '' ?>
             <?= $componentClasses ?>"
                 data-items-per-view="<?= $itemsPerView ?>"
                <?= $itemsPerViewMobile ? 'data-mobile-items-per-view="' . $itemsPerViewMobile . '"' : '' ?>
                 data-is-slider="<?= $isSlider ?>"
                 data-mobile-is-slider="<?= $isSliderMobile ?>">

                <div class="cs-image-teaser__carousel">
                    <div class="cs-image-teaser__wrapper cs-image-teaser__wrapper--content-display-<?= $displayVariant ?>">
                        <ul class="cs-image-teaser__slides">

                            <?php foreach ($slides as $slide): ?>
                                <li class="cs-image-teaser__slide cs-image-teaser__slide--scheme-<?= $slide->getData('colorScheme') ?> <?= $slide->getSrc() ? 'cs-image-teaser__slide--image-uploaded' : '' ?>">
                                    <?php if ($slide->getHref()): ?>
                                    <a href="<?= $slide->getHref() ?>" class="cs-image-teaser__slide-link">
                                        <?php endif; ?>

                                        <?php
                                        $imageSrc = $slide->getSrc();

                                        if ($imageSrc and !$slide->isSvg()) {
                                            $imageSrc = ($isSlider and $isSliderMobile) ? '' : 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
                                        }
                                        ?>
                                        <?php if ($slide->getSrc()): ?>
                                            <figure class="cs-image-teaser__figure">
                                                <img
                                                        class="cs-image-teaser__image | <?= ($isSlider and $isSliderMobile) ? 'swiper-lazy' : 'lazyload' ?>"
                                                        src="<?= $imageSrc ?>"
                                                    <?php if (!$slide->isSvg()): ?> data-src="<?= $slide->getSrc() ?>" <?php endif; ?>
                                                    <?php if ($slide->getSrcSet() and !$slide->isSvg()): ?>
                                                        data-srcset="<?= $slide->getSrcSet() ?>"
                                                    <?php endif; ?>
                                                    <?php if ($sizes and !$slide->isSvg()): ?>
                                                        sizes="<?= $sizes ?>"
                                                    <?php endif; ?>
                                                        alt="<?= $slide->getAlt() ?>"
                                                    <?php if ($slide->getWidth()): ?> width="<?= $slide->getWidth() ?>" <?php endif; ?>
                                                    <?php if ($slide->getHeight()): ?> height="<?= $slide->getHeight() ?>" <?php endif; ?>
                                                >
                                                <noscript>
                                                    <img
                                                            class="cs-image-teaser__image"
                                                            src="<?= $slide->getSrc() ?>"
                                                            <?php if ($slide->getSrcSet()): ?>srcset="<?= $slide->getSrcSet() ?>" <?php endif; ?>
                                                            <?php if ($sizes): ?>sizes="<?= $sizes ?>"<?php endif; ?>
                                                            alt="<?= $slide->getAlt() ?>"
                                                        <?php if ($slide->getWidth()): ?> width="<?= $slide->getWidth() ?>" <?php endif; ?>
                                                        <?php if ($slide->getHeight()): ?> height="<?= $slide->getHeight() ?>" <?php endif; ?>
                                                    >
                                                </noscript>
                                            </figure>
                                        <?php endif; ?>

                                        <div class="cs-image-teaser__content-wrapper cs-image-teaser__content-wrapper--content-display-scenario-<?= $slide->getData('displayVariant') ?>">
                                            <div class="cs-image-teaser__content">
                                                <?php if ($slide->getHeadline()): ?>
                                                    <h2 class="cs-image-teaser__headline"><?= $slide->getHeadline() ?></h2>
                                                <?php endif; ?>

                                                <?php if ($slide->getSubheadline()): ?>
                                                    <p class="cs-image-teaser__subheadline"><?= $slide->getSubheadline() ?></p>
                                                <?php endif; ?>

                                                <?php if ($slide->getParagraph()): ?>
                                                    <p class="cs-image-teaser__text"><?= $slide->getParagraph() ?></p>
                                                <?php endif; ?>

                                                <?php if ($slide->getHref() and $slide->getData('ctaLabel')): ?>
                                                    <div class="cs-image-teaser__cta">
                                                        <span role="button" class="cs-image-teaser__cta-button">
                                                            <span class="cs-image-teaser__cta-button-span"><?= $slide->getData('ctaLabel') ?></span>
                                                            <?= $this->getLayout()
                                                                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                                                ->setIconUrl($block->getVar('cms_teaser/cta_button_icon_path'))
                                                                ->setCssClass('cs-image-teaser__cta-button-icon')
                                                                ->setInlined(true)
                                                                ->toHtml(); 
                                                        ?>
                                                        </span>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <?php if ($slide->getHref()): ?>
                                    </a>
                                <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>

                    <?php if ($block->getVar('cms_teaser/show_navigation') && ($isSlider or $isSliderMobile)): ?>
                        <button class="cs-image-teaser__nav cs-image-teaser__nav--prev <?= $block->getVar('cms_teaser/navigation/arrows/prev/additional_css_classes') ?>"
                                type="button">
                            <?= $this->getLayout()
                                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                ->setIconUrl($block->getVar('cms_teaser/navigation/arrows/prev/path'))
                                ->setCssClass('cs-image-teaser__nav-icon')
                                ->setInlined(true)
                                ->toHtml(); 
                            ?>
                        </button>
                        <button class="cs-image-teaser__nav cs-image-teaser__nav--next <?= $block->getVar('cms_teaser/navigation/arrows/next/additional_css_classes') ?>"
                                type="button">
                            <?= $this->getLayout()
                                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                ->setIconUrl($block->getVar('cms_teaser/navigation/arrows/next/path'))
                                ->setCssClass('cs-image-teaser__nav-icon')
                                ->setInlined(true)
                                ->toHtml(); 
                            ?>
                        </button>
                    <?php endif; ?>

                </div>

                <?php if($block->getVar('cms_teaser/pagination/show') && ($isSlider or $isSliderMobile)): ?>
                    <ul class="cs-image-teaser__pagination <?= $block->getVar('cms_teaser/pagination/additional_css_classes') ?>"></ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>