<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser */
/** @var $viewModel \MageSuite\ContentConstructorFrontend\Model\Component\DailyDealTeaser */
$viewModel = $block->getViewModel();

$visibility = $block->getVisibilityClass();

$product = $viewModel->getProduct();

$layout = $this->getLayout();

$componentClasses = $block->getSkipSpacing() ? ' cs-daily-deal-teaser--skip-spacing' : '';
$componentClasses .= ' ' . $block->getVar('daily_deal_teaser/additional_css_classes');
?>

<?php if (!empty($product)): ?>
    <div <?= $visibility ? 'class="' . $visibility . '"' : ''; ?>>
        <div class="cs-container cs-container--daily-deal-teaser">
            <div class="cs-container__inner">
                <div class="cs-daily-deal-teaser<?= $componentClasses ?>">
                    <aside class="cs-daily-deal-teaser__aside-image">
                            <?= $layout
                                ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/image.phtml')
                                ->toHtml();
                            ?>
                    </aside>
                    <section class="cs-daily-deal-teaser__main">
                        <div class="cs-daily-deal-teaser__details">
                            <?= $layout
                                ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/details.phtml')
                                ->toHtml();
                            ?>
                        </div>

                        <div class="cs-daily-deal-teaser__description">
                            <?= $layout
                                ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/description.phtml')
                                ->toHtml();
                            ?>
                        </div>
                        <div class="cs-daily-deal-teaser__actions">
                            <?= $layout
                                    ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/actions.phtml')
                                    ->toHtml();
                                ?>
                        </div>
                    </section>
                </div>

                <?php if ($block->getVar('daily_deal_teaser/expired_notice/show')): ?>
                <div class="cs-daily-deal-teaser cs-daily-deal-teaser--expired">
                    <?= $block->getVar('daily_deal_teaser/expired_notice/content'); ?>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

<?php endif; ?>
