<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser */
$componentConfiguration = $block->getData();

/** @var $viewModel \MageSuite\ContentConstructorFrontend\Model\Component\DailyDealTeaser */
$viewModel = $block->getViewModel();

$visibility = $block->getVisibilityClass();

$product = $viewModel->getProduct();

$layout = $this->getLayout();

$componentClasses = $block->getSkipSpacing() ? ' cs-daily-deal-teaser--skip-spacing' : '';
$componentClasses .= ' ' . $block->getVar('daily_deal_teaser/additional_css_classes');

$containerClasses = $block->getContainerMix();
if (isset($componentConfiguration['cc_css_classes'])):
    $containerClasses .= ' ' . $componentConfiguration['cc_css_classes'];
endif;
?>

<?php if (!empty($product) && $product['productObject']->getIsSalable() && $product['dailyDealOffer']['deal']): ?>
    <?= $block->getCssOnce('css/daily-deal-teaser.css'); ?>

    <div class="cs-container cs-container--daily-deal-teaser<?= $containerClasses ?><?= $visibility ? ' ' .$visibility : ''; ?>">
        <div class="cs-container__inner">
            <div class="cs-daily-deal-teaser<?= $componentClasses ?>">
                <aside class="cs-daily-deal-teaser__aside-image">
                        <?= $layout
                            ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                            ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/image.phtml')
                            ->setData($block->getData())
                            ->toHtml();
                        ?>
                </aside>
                <section class="cs-daily-deal-teaser__main">
                    <div class="cs-daily-deal-teaser__details">
                        <?= $layout
                            ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                            ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/product_details.phtml')
                            ->setData($block->getData())
                            ->toHtml();
                        ?>
                    </div>

                    <div class="cs-daily-deal-teaser__description">
                        <?= $layout
                            ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                            ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/product_description.phtml')
                            ->setData($block->getData())
                            ->toHtml();
                        ?>
                    </div>
                    <div class="cs-daily-deal-teaser__actions">
                        <?= $layout
                                ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/daily_deal_stock_status.phtml')
                                ->setData($block->getData())
                                ->toHtml();
                            ?>
                        <?= $layout
                                ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/daily_deal_counter.phtml')
                                ->setData($block->getData())
                                ->toHtml();
                            ?>
                        <?= $layout
                                ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/daily_deal_teaser/cta.phtml')
                                ->setData($block->getData())
                                ->toHtml();
                            ?>
                    </div>
                </section>
            </div>

            <?php if ($block->getVar('daily_deal_teaser/expired_notice/show')): ?>
            <div class="cs-daily-deal-teaser cs-daily-deal-teaser--expired">
                <?= $block->getVar('daily_deal_teaser/expired_notice/content'); ?>
            </div>
            <?php endif; ?>
        </div>
    </div>

<?php endif; ?>
