<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\Headline */
/** @var $viewModel \MageSuite\ContentConstructorFrontend\Model\Component\Headline */
$viewModel = $block->getViewModel();
$visibility = $block->getVisibilityClass();

$componentConfiguration = $block->getData();
$tag = $viewModel->getHeadingTag();

$componentClasses = $block->getSkipSpacing() ? ' cs-headline--skip-spacing' : ''; 
$componentClasses .= ' ' . $block->getVar('headline/additional_css_classes');

$containerClasses = $block->getContainerMix();
if (isset($componentConfiguration['cc_css_classes'])):
    $containerClasses .= ' ' . $componentConfiguration['cc_css_classes'];
endif;
?>

<div class="cs-container cs-container--headline<?= $containerClasses ?><?= $visibility ? ' ' .$visibility : ''; ?>">
    <div class="cs-container__inner">
        <div class="cs-headline<?= $componentClasses ?>">
            <<?=$tag?> class="cs-headline__title"><?= $viewModel->getTitle() ?></<?=$tag?>>
            <?php if ($viewModel->getSubtitle()): ?>
                <p class="cs-headline__subtitle"><?= $viewModel->getSubtitle() ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>

