<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\HeroCarousel */
$componentConfiguration = $block->getData();

/** @var \MageSuite\ContentConstructorFrontend\Model\Component\HeroCarousel $viewModel */
$viewModel = $block->getViewModel();
$visibility = $block->getVisibilityClass();
$mobileDisplayVariantClass = '';

if ($componentConfiguration['mobileDisplayVariant']['id'] == 'list') {
    $mobileDisplayVariantClass = 'cs-hero--as-list-mobile';
} else if ($componentConfiguration['mobileDisplayVariant']['id'] == 'hidden') {
    $mobileDisplayVariantClass = 'cs-hero--hidden-mobile';
}

?>

<div <?php if (!empty($visibility)): ?> class="<?=$visibility?>" <?php endif; ?>>
    <div class="cs-container cs-container--hero">
        <div class="cs-container__inner">
            <div class="cs-hero <?= $mobileDisplayVariantClass ?> <?= $block->getVar('hero_carousel/mix'); ?>">
                <div class="cs-hero__carousel">
                    <div class="cs-hero__wrapper">
                        <ul class="cs-hero__slides">

                            <?php foreach ($viewModel->getSlides() as $slide): ?>
                                <?php
                                $imageSrc = $slide->getSrc();
                                $href = $slide->getHref();
                                ?>
                                <li class="cs-hero__slide cs-hero__slide--scheme-<?= $slide->getData('colorScheme') ?> <?= $imageSrc ? 'cs-hero__slide--image-uploaded' : '' ?>">
                                    <?php if ($href): ?>
                                    <a href="<?= $href ?>" class="cs-hero__slide-link">
                                        <?php endif; ?>

                                        <?php if ($imageSrc): ?>
                                            <figure class="cs-hero__figure">
                                                <img
                                                        class="cs-hero__image"
                                                        src="<?= $imageSrc ?>"
                                                        srcset="<?= $slide->getSrcSet() ?>"
                                                        sizes="<?= $block->getVar('hero_carousel/sizes'); ?>"
                                                        alt="<?= $slide->getAlt() ?>"
                                                >
                                            </figure>
                                        <?php endif; ?>

                                        <div class="cs-hero__content-wrapper cs-hero__content-wrapper--<?= $slide->getData('displayVariant') ?>">
                                            <div class="cs-hero__content">
                                                <?php if ($slide->getHeadline()): ?>
                                                    <h2 class="cs-hero__headline"><?= $slide->getHeadline() ?></h2>
                                                <?php endif; ?>

                                                <?php if ($slide->getSubheadline()): ?>
                                                    <p class="cs-hero__subheadline"><?= $slide->getSubheadline() ?></p>
                                                <?php endif; ?>

                                                <?php if ($slide->getParagraph()): ?>
                                                    <p class="cs-hero__text"><?= $slide->getParagraph() ?></p>
                                                <?php endif; ?>

                                                <?php if ($slide->getHref() and $slide->getData('ctaLabel')): ?>
                                                    <div class="cs-hero__cta">
                                                <span role="button"
                                                      class="cs-button cs-button--type_long cs-button--look_default">
                                                    <span class="cs-button__span"><?= $slide->getData('ctaLabel') ?></span>
                                                    <?php if($block->getVar('hero_carousel/cta_button_icon/show')): ?>
                                                        <svg class="cs-button__icon">
                                                            <use xlink:href="<?= $block->getVar('hero_carousel/cta_button_icon/path') ?>"></use>
                                                        </svg>
                                                    <?php endif; ?>
                                                </span>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <?php if ($href): ?>
                                    </a>
                                <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>

                <?php if($block->getVar('hero_carousel/navigation/show')): ?>
                    <button class="cs-hero__nav cs-hero__nav--prev <?= $block->getVar('hero_carousel/navigation/arrows/prev/mix') ?>"
                            type="button">
                        <svg class="cs-hero__nav-icon">
                            <use xlink:href="<?php echo $block->getVar('hero_carousel/navigation/arrows/prev/path'); ?>"></use>
                        </svg>
                    </button>
                    <button class="cs-hero__nav cs-hero__nav--next <?= $block->getVar('hero_carousel/navigation/arrows/next/mix') ?>"
                            type="button">
                        <svg class="cs-hero__nav-icon">
                            <use xlink:href="<?php echo $block->getVar('hero_carousel/navigation/arrows/next/path'); ?>"></use>
                        </svg>
                    </button>
                <?php endif; ?>


                <?php if($block->getVar('hero_carousel/pagination/show')): ?>
                    <ul class="cs-hero__pagination <?= $block->getVar('hero_carousel/pagination/mix') ?>"></ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
