<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\Icon */
$iconConfiguration = $block->getData();
// Build JS config
$jsSettings = $block->getVar('icon/js');
if (empty($jsSettings)) {
    $jsSettings = [];
}

echo $this->getLayout()
    ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
    ->setData($iconConfiguration)
    ->setComponentType('icon')
    ->setMix('cs-image-teaser--icon ' . $block->getMix())
    ->setContainerMix('cs-container--icon ' . $block->getContainerMix())
    ->setAdditionalJsSettings($jsSettings)
    ->toHtml();
?>
