<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser */
$viewModel = $block->getViewModel();
$visibility = $block->getVisibilityClass();
$maxContentWidth = $block->getVar('max_content_width');

$imageTeaser = $block->getData();
$slides = $viewModel->getSlides();

$componentType = $block->getComponentType() ?? 'image_teaser';

$desktopLayout = $imageTeaser['scenario']['desktopLayout']['id'];
$mobileLayout = $imageTeaser['scenario']['mobileLayout']['id'];

$teaserWidth = $imageTeaser['scenario']['teaserWidth']['id'];

$mosaicProportions = isset($imageTeaser['scenario']['proportions']) && isset($imageTeaser['scenario']['proportions']['id']) ? $imageTeaser['scenario']['proportions']['id'] : '';

$itemsPerRow = $desktopLayout;
$itemsPerView = $itemsPerRow;

$itemsPerRowMobile = 2;
$itemsPerViewMobile = $block->getItemsPerViewMobile() ?? 1;

$isSlider = false;
$isSliderMobile = false;

if (in_array($mobileLayout, ['mobile-large', 'mobile-slider', 'mobile-in-columns'])) {
    $itemsPerRowMobile = 1;
}

if (($teaserWidth == 'window-slider' || $teaserWidth == 'container-slider') && count($slides) > 1) {
    $isSlider = true;
}

if ($mobileLayout == 'mobile-slider' && count($slides) > 1) {
    $isSliderMobile = true;
}

$componentClasses = $block->getMix();
$componentClasses .= $block->getSkipSpacing() ? ' cs-image-teaser--skip-spacing' : '';
$componentClasses .= ' ' . $block->getVar('image_teaser/additional_css_classes');
if ($teaserWidth == 'container' or $teaserWidth == 'container-slider') {
    $componentClasses .= ' cs-image-teaser--container-width';
}

$contentPlacement = $imageTeaser['scenario']['contentPlacement']['id'];

$sizesMobile = '(max-width: 48em) 100vw';
$sizesDesktop = sprintf('%svw', 100 / $itemsPerViewMobile);

if ($teaserWidth == 'window-slider') {
    $sizesMobile = '(max-width: 48em) 80vw';
    $sizesDesktop = (80 / $itemsPerView) . 'vw';
} else if ($teaserWidth == 'container') {
    $sizesDesktop = '(min-width: ' . $maxContentWidth . 'px) ' . ($maxContentWidth / $itemsPerView) . 'px, ' . $sizesDesktop;
}

$sizes = $sizesMobile . ', ' . $sizesDesktop;

$containerClasses = ($teaserWidth == 'window' || $teaserWidth == 'window-slider') ? ' cs-container--image-teaser-window-width' : '';

$containerClasses .= ' ' . $block->getContainerMix();
if (isset($imageTeaser['cc_css_classes'])):
    $containerClasses .= ' ' . $imageTeaser['cc_css_classes'];
endif;

// Init JS config
$jsSettings = $block->getVar('image_teaser/js');
if (empty($jsSettings)) {
    $jsSettings = [];
}

// Modify css classes based on settings
if ($block->getVar($componentType.'/use_whole_screen') == 'true') {
    if ($teaserWidth != 'container') {
        $containerClasses .= ' cs-container--use-whole-screen';
        $jsSettings['useWholeScreen'] = true;
    }
    $componentClasses .= ' cs-image-teaser--use-whole-screen';
}

// Build JS config
$jsSettings['itemsPerView'] = (int)$itemsPerRow;
$jsSettings['itemsCount'] = count($slides);
$jsSettings['componentType'] = $componentType;

// Merge JS config from other components if provided
$additionalJsSettings = $block->getAdditionalJsSettings();
if (!empty($additionalJsSettings)) {
    $jsSettings = array_merge($jsSettings, $additionalJsSettings);
}

$windowWidthClass = ($teaserWidth == 'window' || $teaserWidth == 'window-slider') ? ' cs-image-teaser--window-width' : '';

// Grid teaser
$gridTeaser = $block->getGridTeaser();

if ($gridTeaser) {
    $teaser = $block->getTeaserData();
    $teaserId = $block->getTeaserId();
    $brickClass = $block->getBrickClass();

    $teaserBrickClass = $brickClass . ' ' . $brickClass . '--teaser';
    if($teaser['size']['x'] == 2) {
        $teaserBrickClass .= ' ' .$brickClass . '--x2';
    }
    if($teaser['size']['y'] == 2) {
        $teaserBrickClass .= ' ' . $brickClass . '--y2';
    }
}

$openLinkInNewTab = $block->getOpenLinkInNewTab() ? true : false;
?>

<?= $block->getCssOnce('css/image-teaser.css'); ?>

<?php if ($gridTeaser): ?>
<li class="<?= $teaserBrickClass ?>" id="<?= $teaserId ?>">
<?php endif; ?>
    <?= $this->getLayout()
        ->createBlock(\Magento\Framework\View\Element\Template::class)
        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/hotspots/before_container.phtml')
        ->setImageTeaser($imageTeaser)
        ->setIsSlider($isSlider)
        ->setIsSliderMobile($isSliderMobile)
        ->setContentPlacement($contentPlacement)
        ->toHtml();
    ?>

    <div class="cs-container cs-container--image-teaser<?= $isSlider ? ' cs-container--image-teaser-slider' : '' ?><?= $containerClasses ?><?= $visibility ? ' ' .$visibility : ''; ?>">
        <div class="cs-container__inner">
            <?= $this->getLayout()
                ->createBlock(\Magento\Framework\View\Element\Template::class)
                ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/hotspots/before_component.phtml')
                ->setImageTeaser($imageTeaser)
                ->setIsSlider($isSlider)
                ->setIsSliderMobile($isSliderMobile)
                ->setContentPlacement($contentPlacement)
                ->toHtml();
            ?>

            <div class="cs-image-teaser <?= $windowWidthClass ?>
                cs-image-teaser--items-in-row-<?= $itemsPerRow ?>
                cs-image-teaser--items-in-row-mobile-<?= $itemsPerRowMobile ?>
                <?= $isSlider ? 'cs-image-teaser--slider' : '' ?>
                <?= $isSliderMobile ? 'cs-image-teaser--slider-mobile' : '' ?>
                <?= $teaserWidth == 'window-slider' ? 'cs-image-teaser--full-width-slider' : '' ?>
                <?= $componentClasses ?>"
                <?php if($isSlider || ($isSliderMobile && $block->getVar($componentType.'/js/usePagination'))): ?>
                data-mage-init='{ "ccImageTeaser": <?= json_encode($jsSettings) ?> }'
                <?php endif; ?>
            >
                <div class="cs-image-teaser__slides-wrapper">
                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/hotspots/before_slides.phtml')
                        ->setImageTeaser($imageTeaser)
                        ->setIsSlider($isSlider)
                        ->setIsSliderMobile($isSliderMobile)
                        ->setContentPlacement($contentPlacement)
                        ->toHtml();
                    ?>

                    <?php if (($isSlider or $isSliderMobile) && $block->getVar($componentType.'/navigation/show')): ?>
                        <?= $this->getLayout()
                            ->createBlock(\Magento\Framework\View\Element\Template::class)
                            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/nav-prev.phtml')
                            ->setIcon($block->getVar('image_teaser/navigation/arrows/prev/path'))
                            ->setImageTeaserData($imageTeaser)
                            ->toHtml();
                        ?>
                    <?php endif; ?>

                    <ul class="cs-image-teaser__slides cs-image-teaser__slides<?= $mosaicProportions != '' ? ' cs-image-teaser__slides--mosaic-scenario-' . $mosaicProportions : '' ?> <?= $componentType == 'teaser_and_text' ? 'cs-image-teaser__slides--mobile_' . $mobileLayout : '' ?>">
                        <?php $slideIndex = 0; ?>
                        <?php foreach ($slides as $slide): ?>
                            <?= $this->getLayout()
                                ->createBlock(\Magento\Framework\View\Element\Template::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/image_teaser_slide.phtml')
                                ->setSlide($slide)
                                ->setImageTeaser($imageTeaser)
                                ->setIsSlider($isSlider)
                                ->setIsSliderMobile($isSliderMobile)
                                ->setContentPlacement($contentPlacement)
                                ->setOpenLinkInNewTab($openLinkInNewTab)
                                ->setSlideIndex($slideIndex)
                                ->toHtml();
                            ?>
                            <?php $slideIndex++; ?>
                        <?php endforeach; ?>
                    </ul>

                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/hotspots/after_slides.phtml')
                        ->setImageTeaser($imageTeaser)
                        ->setIsSlider($isSlider)
                        ->setIsSliderMobile($isSliderMobile)
                        ->setContentPlacement($contentPlacement)
                        ->toHtml();
                    ?>

                    <?php if (($isSlider or $isSliderMobile) && $block->getVar($componentType.'/navigation/show')): ?>
                        <?= $this->getLayout()
                            ->createBlock(\Magento\Framework\View\Element\Template::class)
                            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/nav-next.phtml')
                            ->setIcon($block->getVar('image_teaser/navigation/arrows/next/path'))
                            ->setImageTeaserData($imageTeaser)
                            ->toHtml();
                        ?>
                    <?php endif; ?>
                </div>

                <?php if (($isSlider or $isSliderMobile) && $block->getVar($componentType.'/js/usePagination')): ?>
                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/pagination.phtml')
                        ->setImageTeaserData($imageTeaser)
                        ->setIsSlider($isSlider)
                        ->setIsSliderMobile($isSliderMobile)
                        ->toHtml();
                    ?>

                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/hotspots/after_pagination.phtml')
                        ->setImageTeaser($imageTeaser)
                        ->setIsSlider($isSlider)
                        ->setIsSliderMobile($isSliderMobile)
                        ->setContentPlacement($contentPlacement)
                        ->toHtml();
                    ?>
                <?php endif; ?>
            </div>
        </div>
        <?= $this->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/elements/hotspots/after_component.phtml')
            ->setImageTeaser($imageTeaser)
            ->setIsSlider($isSlider)
            ->setIsSliderMobile($isSliderMobile)
            ->setContentPlacement($contentPlacement)
            ->toHtml();
        ?>
    </div>
<?php if ($gridTeaser): ?>
</li>
<?php endif; ?>
