<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser */
$viewModel = $block->getViewModel();
$visibility = $block->getVisibilityClass();
$maxContentWidth = $block->getVar('max_content_width');

$imageTeaser = $block->getData();

$desktopLayout = $imageTeaser['scenario']['desktopLayout']['id'];
$mobileLayout = $imageTeaser['scenario']['mobileLayout']['id'];

$teaserWidth = $imageTeaser['scenario']['teaserWidth']['id'];

$itemsPerRow = $desktopLayout;
$itemsPerView = $itemsPerRow;

$itemsPerRowMobile = 2;
$itemsPerViewMobile = 1;

$isSlider = false;
$isSliderMobile = false;

$mix = $block->getMix();

if (in_array($mobileLayout, ['mobile-large', 'mobile-slider', 'mobile-in-columns'])) {
    $itemsPerRowMobile = 1;
}

if ($teaserWidth == 'window-slider' || $teaserWidth == 'container-slider') {
    $isSlider = true;
}

if ($mobileLayout == 'mobile-slider') {
    $isSliderMobile = true;
}

$componentClasses = $block->getMix();
$componentClasses .= $block->getSkipSpacing() ? ' cs-image-teaser--skip-spacing' : ''; 
$componentClasses .= ' ' . $block->getVar('image_teaser_next/additional_css_classes');

$contentPlacement = $imageTeaser['scenario']['contentPlacement']['id'];

$sizesMobile = '(max-width: 48em) 100vw';
$sizesDesktop = sprintf('%svw', 100 / $itemsPerViewMobile);

if ($teaserWidth == 'window-slider') {
    $sizesMobile = '(max-width: 48em) 80vw';
    $sizesDesktop = (80 / $itemsPerView) . 'vw';
} else if ($teaserWidth == 'container') {
    $sizesDesktop = '(min-width: ' . $maxContentWidth . 'px) ' . ($maxContentWidth / $itemsPerView) . 'px, ' . $sizesDesktop;
}

$sizes = $sizesMobile . ', ' . $sizesDesktop;
?>

<div <?= $visibility ? 'class="' . $visibility . '"' : ''; ?>>
    <div class="cs-container cs-container--image-teaser<?= ($teaserWidth == 'window' || $teaserWidth == 'window-slider') ? ' cs-container--image-teaser-window-width' : '' ?>">
        <?php if ($teaserWidth == 'container' or $teaserWidth == 'container-slider'): ?>
        <div class="cs-container__inner">
        <?php endif; ?>
            <div class="cs-image-teaser
             cs-image-teaser--items-in-row-<?= $itemsPerRow ?>
             cs-image-teaser--items-in-row-mobile-<?= $itemsPerRowMobile ?>
             <?= $isSlider ? 'cs-image-teaser--slider' : '' ?>
             <?= $teaserWidth == 'window-slider' ? 'cs-image-teaser--full-width-slider' : '' ?>
             <?= $componentClasses ?>"
                data-items-per-view="<?= $itemsPerView ?>"
                <?= $itemsPerViewMobile ? 'data-mobile-items-per-view="' . $itemsPerViewMobile . '"' : '' ?>
                data-is-slider="<?= $isSlider ?>"
                data-mobile-is-slider="<?= $isSliderMobile ?>"
                data-layout="<?= $contentPlacement ?>">

                <div class="cs-image-teaser__carousel">
                    <div class="cs-image-teaser__wrapper cs-image-teaser__wrapper--content-<?= $contentPlacement ?>">
                        <ul class="cs-image-teaser__slides">
                            <?php foreach ($viewModel->getSlides() as $slide): ?>
                                <?= $this->getLayout()
                                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/image_teaser_slide.phtml')
                                        ->setSlide($slide)
                                        ->setIsSlider($isSlider)
                                        ->setIsSliderMobile($isSliderMobile)
                                        ->setContentPlacement($contentPlacement)
                                        ->toHtml(); 
                                ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>

                    <?php if (($isSlider or $isSliderMobile) && $block->getVar('image_teaser/navigation/show')): ?>
                        <button class="cs-image-teaser__nav cs-image-teaser__nav--prev"
                                type="button">
                            <?= $this->getLayout()
                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                    ->setIconUrl($block->getVar('image_teaser/navigation/arrows/prev/path'))
                                    ->setCssClass('cs-image-teaser__nav-icon')
                                    ->setInlined(true)
                                    ->setLazyLoaded(false)
                                    ->toHtml(); 
                            ?>
                        </button>
                        <button class="cs-image-teaser__nav cs-image-teaser__nav--next"
                                type="button">
                            <?= $this->getLayout()
                                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                ->setIconUrl($block->getVar('image_teaser/navigation/arrows/next/path'))
                                ->setCssClass('cs-image-teaser__nav-icon')
                                ->setInlined(true)
                                ->setLazyLoaded(false)
                                ->toHtml(); 
                            ?>
                        </button>
                    <?php endif; ?>

                </div>

                <?php if (($isSlider or $isSliderMobile) && $block->getVar('image_teaser/pagination/show')): ?>
                    <ul class="cs-image-teaser__pagination <?= $block->getVar('image_teaser/pagination/additional_css_classes') ?>"></ul>
                <?php endif; ?>
                <?php if ($teaserWidth == 'container' or $teaserWidth == 'container-slider'): ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
