<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\InstagramFeed */
$data = $block->getData();
/** @var \MageSuite\ContentConstructorFrontend\Model\Component\InstagramFeed $viewModel */
$viewModel = $block->getViewModel();


$numberOfSlides = $data['scenario']['numberOfSlides'];
$data['items'] = $viewModel->getFeedData($numberOfSlides);

if(!empty($data['items'])) {
   echo $this->getLayout()
       ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
       ->setData($data)
       ->setMix('cs-image-teaser--instagram-feed ' . $block->getMix())
       ->setContainerMix('cs-container--instagram-feed ' . $block->getContainerMix())
       ->toHtml();
}
?>