<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\InstagramFeed */
$data = $block->getData();
/** @var \MageSuite\ContentConstructorFrontend\Model\Component\InstagramFeed $viewModel */
$viewModel = $block->getViewModel();

$numberOfSlides = $data['scenario']['numberOfSlides'];
$data['items'] = $viewModel->getFeedData($numberOfSlides);
$isConsentRequired = $viewModel->isInstagramConsentRequired() ?? false;

if(!empty($data['items'])) {
   echo $this->getLayout()
       ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
       ->setData($data)
       ->setComponentType('instagram')
       ->setMix('cs-image-teaser--instagram-feed ' . $block->getMix())
       ->setContainerMix('cs-container--instagram-feed ' . $block->getContainerMix())
       ->setOpenLinkInNewTab(true)
       ->setIsConsentRequired($isConsentRequired)
       ->toHtml();
}
?>

<?php if ($isConsentRequired): ?>
    <script type="text/x-magento-init">
    {
        ".cs-image-teaser--instagram-feed": {
            "ccInstagram": {}
        }
    }
    </script>
<?php endif; ?>
