<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\InstagramFeed */

// echo $this->getLayout()
//     ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
//     ->setData($block->getData())
//     ->setMix('cs-image-teaser--instagram-feed ' . $block->getMix())
//     ->setContainerMix('cs-container--instagram-feed ' . $block->getContainerMix())
//     ->toHtml(); 
?>