<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\Mosaic */
$componentConfiguration = $block->getData();
$componentConfiguration['jsConfig'] = $block->getVar('mosaic/js_config');

echo $this->getLayout()
    ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
    ->setData($componentConfiguration)
    ->setMix('cs-image-teaser--mosaic ' . $block->getMix())
    ->setContainerMix('cs-container--mosaic ' . $block->getContainerMix())
    ->toHtml();
?>
