<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\Mosaic */
$componentConfiguration = $block->getData();

$imageTeaser = $block->getLayout()
    ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser::class)
    ->setData($componentConfiguration)
    ->setComponentType('mosaic')
    ->setMix('cs-image-teaser--mosaic ' . $block->getMix())
    ->setContainerMix('cs-container--mosaic ' . $block->getContainerMix());

echo $imageTeaser->toHtml();

$block->addIdentities($imageTeaser->getIdentities());
?>
