<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\Mosaic */
$componentConfiguration = $block->getData();

echo $this->getLayout()
    ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
    ->setData($componentConfiguration)
    ->setComponentType('mosaic')
    ->setMix('cs-image-teaser--mosaic ' . $block->getMix())
    ->setContainerMix('cs-container--mosaic ' . $block->getContainerMix())
    ->toHtml();
?>
