<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\Paragraph */
$componentConfiguration = $block->getData();

/** @var \MageSuite\ContentConstructorFrontend\Model\Component\Paragraph $viewModel */
$viewModel = $block->getViewModel();
$visibility = $block->getVisibilityClass();

$componentClasses = $block->getSkipSpacing() ? ' cs-paragraph--skip-spacing' : '';
$componentClasses .= ' ' . $block->getVar('paragraph/additional_css_classes');

$containerClasses = $block->getContainerMix();
if (isset($componentConfiguration['cc_css_classes'])):
    $containerClasses .= ' ' . $componentConfiguration['cc_css_classes'];
endif;

$includeStylesInComponent = $block->getVar('paragraph/include_styles_in_component');
?>

<?php if ($includeStylesInComponent): ?>
    <?= $block->getCssOnce('css/paragraph.css'); ?>
<?php endif; ?>

<div class="cs-container cs-container--paragraph<?= $containerClasses ?><?= $visibility ? ' ' .$visibility : ''; ?>">
    <div class="cs-container__inner">
        <div class="cs-paragraph cs-paragraph--cols-<?=$viewModel->getColumns()?> cs-paragraph--mode-<?=$componentConfiguration['scenarios']['reading']['id'] ?? ''?><?= $componentClasses ?> | cs-cms-block" data-mage-init='{ "ccParagraph": {} }'>
            <?=$viewModel->getContent()?>
        </div>
    </div>
</div>
