<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\ProductTeaser */
$componentConfiguration = $block->getData();

/** @var $viewModel \MageSuite\ContentConstructorFrontend\Model\Component\ProductTeaser */
$viewModel = $block->getViewModel();
$product = $viewModel->getProductObject();
$visibility = $block->getVisibilityClass();
$containerClasses = $block->getContainerMix();

if (isset($componentConfiguration['cc_css_classes'])) {
    $containerClasses .= ' ' . $componentConfiguration['cc_css_classes'];
}
?>
<?= $block->getCssOnce('css/product-teaser.css'); ?>
<div class="cs-container cs-container--product-teaser<?=/* @noEscape */ $containerClasses ?><?=/* @noEscape */ $visibility ? ' ' .$visibility : ''; ?>">
    <div class="cs-container__inner">
        <div class="cs-product-teaser">
                <?= $this->getLayout()
                    ->createBlock(\MageSuite\ProductTile\Block\Tile::class)
                    ->setAreas(['teaser'])
                    ->setViewMode('teaser')
                    ->setSection('teaser')
                    ->render($product);
                ?>
        </div>
    </div>
</div>
