<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\ProductFinder */
$componentConfiguration = $block->getData();
/** @var \MageSuite\ContentConstructorFrontend\Model\Component\ProductFinder $viewModel */
$viewModel = $block->getViewModel();

$visibility = $block->getVisibilityClass();
$steps = $viewModel->getSteps();
$totalSteps = count($steps);
$i = 0;

$componentClasses = $block->getSkipSpacing() ? ' cs-product-finder--skip-spacing' : '';
$componentClasses .= ' ' . $block->getVar('product_finder/additional_css_classes');

$jsSettings = json_encode($block->getVar('product_finder/js') ?: '{}');

$containerClasses = $block->getContainerMix();
if (isset($componentConfiguration['cc_css_classes'])):
    $containerClasses .= ' ' . $componentConfiguration['cc_css_classes'];
endif;

$includeStylesInComponent = $block->getVar('product_finder/include_styles_in_component');
?>

<?php if ($includeStylesInComponent): ?>
    <?= $block->getCssOnce('css/product-finder.css'); ?>
<?php endif; ?>

<div class="cs-container cs-container--product-finder<?= $containerClasses ?><?= $visibility ? ' ' .$visibility : ''; ?>">
    <div class="cs-container__inner">
        <div class="cs-product-finder<?= $componentClasses ?>" data-mage-init='{ "ccProductFinder": <?= $jsSettings ?> }'>
        <?php foreach($steps as $step): ?>
            <?php

                $stepOptionsPerRow = array_merge($viewModel->getData('optionsPerRow'), isset($step['optionsPerRow']) ? $step['optionsPerRow'] : []);
                $stepClasses = [];

                $stepClasses[] = "cs-product-finder__step--options-mobile_".$stepOptionsPerRow['mobile'];
                $stepClasses[] = "cs-product-finder__step--options-tablet_".$stepOptionsPerRow['tablet'];
                $stepClasses[] = " cs-product-finder__step--options-desktop_".$stepOptionsPerRow['desktop'];
                $stepClasses[] = $step['additional_css_class'];
                $isLastStep = ($i === $totalSteps - 1);

                if($i == 0) {
                    $stepClasses[] = 'cs-product-finder__step--current';
                }
            ?>
            <article
                class="cs-product-finder__step <?=implode(' ', $stepClasses)?>"
                data-step-id="<?=$step['id']?>"
            >

                <?php if (!empty($step['title']) || !empty($step['description'])): ?>
                    <header class="cs-product-finder__step-header">
                        <?php if (!empty($step['title'])): ?>
                            <h2 class="cs-product-finder__step-title"><?=$step['title']?></h2>
                        <?php endif; ?>
                        <?php if (!empty($step['description'])): ?>
                            <p class="cs-product-finder__step-description"><?=$step['description']?></p>
                        <?php endif; ?>
                    </header>
                <?php endif; ?>

                <div class="cs-product-finder__step-options">
                    <?php foreach($step['options'] as $option): ?>
                    <div
                        class="cs-product-finder__step-option"
                        data-next-step-id="<?=isset($option['next_step']) ? $option['next_step'] : '' ?>"
                        data-attributes='<?=json_encode($option['attributes'])?>'
                        data-category-id='<?=isset($option['category_id']) ? $option['category_id'] : '' ?>'
                        data-category-only='<?=isset($option['category_only']) ? $option['category_only'] : '' ?>'
                        <?php if ($i == 0): ?>
                            tabindex="0"
                        <?php else : ?>
                            tabindex="-1"
                        <?php endif; ?>
                    >
                        <div class="cs-product-finder__option-sizer"></div>
                        <div class="cs-product-finder__option-content">
                            <?php if($option['image']): ?>
                            <img
                                class="cs-product-finder__option-image"
                                src="<?=$option['image']?>"
                                <?= isset($option['label']) ? 'role="presentation"' : 'alt="' . $escaper->escapeHtmlAttr(__('Option')) . '"' ?>
                                <?php if ($i > 0 && !isset($option['imageLoading'])): ?>
                                    loading="lazy"
                                <?php else : ?>
                                    <?php if (isset($option['imageLoading'])): ?>loading="<?= $option['imageLoading'] ?>"<?php endif; ?>
                                <?php endif; ?>
                                <?php if(isset($option['imageWidth'])): ?>width="<?=$option['imageWidth']?>"<?php endif; ?>
                                <?php if(isset($option['imageHeight'])): ?>height="<?=$option['imageHeight']?>"<?php endif; ?>
                            >
                            <?php endif; ?>
                            <?php if($option['label']): ?>
                            <p class="cs-product-finder__option-label"><?=$option['label']?></p>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
                <?php if ($isLastStep): ?>
                    <div class="cs-product-finder__reload-info">
                    <?= $escaper->escapeHtml(__('Clicking one of the options will take you to the results page.')) ?>
                    </div>
                <?php endif; ?>
                <button class="cs-product-finder__back-button" tabindex="-1">
                    <span class="cs-product-finder__back-button-span"><?=__("Go to previous step")?></span>
                    <?= $this->getLayout()
                            ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                            ->setIconUrl($block->getVar('product_finder/button_icon_path'))
                            ->setCssClass('cs-product-finder__back-button-icon')
                            ->setInlined(true)
                            ->toHtml();
                    ?>
                </button>
            </article>
            <?php $i++; ?>
            <?php endforeach; ?>
            <button class="cs-product-finder__back-button" tabindex="-1">
                <span class="cs-product-finder__back-button-span"><?=__("Go to previous step")?></span>
                <?= $this->getLayout()
                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                        ->setIconUrl($block->getVar('product_finder/button_icon_path'))
                        ->setCssClass('cs-product-finder__back-button-icon')
                        ->setInlined(true)
                        ->toHtml();
                ?>
            </button>
            <form class="cs-product-finder__form" method="post" action="<?=$viewModel->getRedirectEndpointUrl()?>"></form>
        </div>
    </div>
</div>
