<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\ProductCarousel */
$componentConfiguration = $block->getData();

/** @var \MageSuite\ContentConstructorFrontend\Model\Component\ProductCarousel $viewModel */
$viewModel = $block->getViewModel();
$visibility = $block->getVisibilityClass();

$navIconNextPath = $block->getVar('product_carousel/navigation/arrows/next/path');
$useWholeScreen = $block->getVar('product_carousel/use_whole_screen') == 'true';

$componentClasses = $block->getSkipSpacing() ? ' cs-products-carousel--skip-spacing' : '';
$componentClasses .= ' ' . $block->getVar('product_carousel/additional_css_classes');

$containerClasses = $block->getContainerMix();
if (isset($componentConfiguration['cc_css_classes'])):
    $containerClasses .= ' ' . $componentConfiguration['cc_css_classes'];
endif;

$viewMode = $block->getData('view_mode') ?? 'grid';
$products = $viewModel->getProducts();
$isList = $viewMode == 'list' ? true : false;
$isSliderMobile = $block->getData('carousel_on_mobile');

// Build JS config
$jsSettings = $block->getVar('product_carousel/js');
if (empty($jsSettings)) {
    $jsSettings = [];
}
$jsSettings['usePagination'] = filter_var($block->getVar('product_carousel/js/usePagination'), FILTER_VALIDATE_BOOL);
$jsSettings['itemsCount'] = count($products);
$jsSettings['columnsConfig'] = $block->getVar('columns/one-column', 'MageSuite_ContentConstructor');
$jsSettings['componentType'] = 'products_carousel';

// modify css classes
if ($useWholeScreen) {
    $containerClasses .= ' cs-container--no-padding';
    $componentClasses .= ' cs-products-carousel--use-whole-screen';
    $jsSettings['useWholeScreen'] = true;
}
?>

<?= $block->getCssOnce('css/products-carousel.css'); ?>

<div class="cs-container cs-container--products-carousel<?= $containerClasses ?><?= $visibility ? ' ' .$visibility : ''; ?>">
    <?php if(!$useWholeScreen): ?>
        <div class="cs-container__inner">
    <?php endif; ?>
        <div class="cs-products-carousel<?= $componentClasses ?>" data-view-mode=<?= $viewMode; ?> data-mage-init='{ "ccProductsCarousel": <?= json_encode($jsSettings) ?> }'>
            <div class="cs-products-carousel__slides-wrapper">
                <?php if ($block->getVar('product_carousel/navigation/show')): ?>
                    <button class="cs-products-carousel__nav cs-products-carousel__nav--prev cs-slider-navigation cs-slider-navigation--prev <?= $block->getVar('product_carousel/navigation/arrows/prev/additional_css_classes') ?>" disabled type="button">
                        <?= $this->getLayout()
                            ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                            ->setIconUrl($block->getVar('product_carousel/navigation/arrows/prev/path'))
                            ->setCssClass('cs-slider-navigation__icon')
                            ->setAltText(__('Previous slide(s)'))
                            ->setInlined(true)
                            ->toHtml();
                        ?>
                    </button>
                <?php endif; ?>
                <ul class="<?php if ($isList): ?>cs-products-list <?php endif; ?><?php if ($isSliderMobile == 'true'): ?>cs-products-list--carousel <?php endif; ?>cs-products-carousel__slides">
                    <?php foreach ($products as $product): ?>
                        <li class="<?php if ($isList): ?>cs-products-list__item <?php endif; ?>cs-products-carousel__slide">
                            <div class="cs-products-carousel__product-tile">
                                <?= $viewModel->renderProductTile($product, null) ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <?php if ($block->getVar('product_carousel/navigation/show')): ?>
                    <button class="cs-products-carousel__nav cs-products-carousel__nav--next cs-slider-navigation cs-slider-navigation--next <?= $block->getVar('product_carousel/navigation/arrows/next/additional_css_classes') ?>" type="button">
                        <?= $this->getLayout()
                            ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                            ->setIconUrl($block->getVar('product_carousel/navigation/arrows/next/path'))
                            ->setCssClass('cs-slider-navigation__icon')
                            ->setAltText(__('Next slide(s)'))
                            ->setInlined(true)
                            ->toHtml();
                        ?>
                    </button>
                <?php endif; ?>
            </div>

            <?php if ($block->getVar('product_carousel/js/usePagination')): ?>
                <div class="cs-slider-pagination cs-products-carousel__pagination <?= $block->getVar('product_carousel/pagination/additional_css_classes') ?>"></div>
            <?php endif; ?>
        </div>
    <?php if(!$useWholeScreen): ?>
        </div>
    <?php endif; ?>
</div>