<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\Separator */
$visibility = $block->getVisibilityClass();

$componentClasses = $block->getSkipSpacing() ? ' cs-separator--skip-spacing' : '';
$componentClasses .= ' ' . $block->getVar('separator/additional_css_classes');
?>

<?= $block->getCssOnce('css/separator.css'); ?>

<div class="cs-container cs-container--separator<?= $visibility ? ' ' .$visibility : ''; ?>">
    <div class="cs-container__inner">
        <hr class="cs-separator<?= $componentClasses ?>" data-mage-init='{ "ccSeparator": {} }'>
    </div>
</div>
