<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\StaticBlock */
$componentConfiguration = $block->getData();

/** @var \MageSuite\ContentConstructorFrontend\Model\Component\StaticBlock $viewModel */
$viewModel = $block->getViewModel();
$visibility = $block->getVisibilityClass();
$resetStyles = $viewModel->getData('resetstyles');
?>

<div <?php if (!empty($visibility)): ?> class="<?=$visibility?>" <?php endif; ?>>
    <div class="cs-container cs-container--static-block">
        <div class="cs-container__inner">
            <div class="<?php if (!$resetStyles): ?>cs-static-cms-block<?php endif; ?> cs-cms-block <?php if ($resetStyles): ?>cs-static-cms-block-resetstyles<?php endif; ?> <?=$block->getVar('static_block/mix');?>">
                <?=$viewModel->getContent()?>
            </div>
        </div>
    </div>
</div>
