<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\TeaserAndTeaser */
$componentConfiguration = $block->getData(); ?>
<?php
/** @var \MageSuite\ContentConstructorFrontend\Model\Component\TeaserAndText $viewModel */
$viewModel = $block->getViewModel();

$componentConfiguration['scenario'] = array_merge_recursive(
    [
        'desktopLayout' => ['id' => '2'],
        'contentPlacement' => ['id' => 'over']
    ],
    $componentConfiguration['scenario'] ?? []
);

?>

<?php
$imageTeaser = $block->getLayout()
    ->createBlock(\MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser::class)
    ->setData($componentConfiguration)
    ->setComponentType('teaser_and_text')
    ->setMix('cs-image-teaser--teaser-and-text ' . $block->getMix())
    ->setContainerMix('cs-container--teaser-and-text ' . $block->getContainerMix());

echo $imageTeaser->toHtml();

$block->addIdentities($imageTeaser->getIdentities());
?>
