<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\TeaserText */

echo $this->getLayout()
    ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
    ->setData($block->getData())
    ->setMix('cs-image-teaser--teaser-text ' . $block->getMix())
    ->setContainerMix('cs-container--teaser-text ' . $block->getContainerMix())
    ->toHtml(); 
?>

hej,hej