<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser */
/** @var $viewModel \MageSuite\ContentConstructorFrontend\Model\Component\DailyDealTeaser */

$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();

$productIsSimple = $product['productObject']->getTypeId() != \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE;

$labels = [
    'day' =>  __('Day'),
    'days' =>  __('Days'),
    'hour' =>  __('Hour'),
    'hours' =>  __('Hours'),
    'minute' =>  __('Min'),
    'minutes' =>  __('Min'),
    'second' =>  __('Sec'),
    'seconds' =>  __('Sec')
];

?>

<?php if ($block->getVar('daily_deal_teaser/show_available_amount_section') && isset($product['dailyDealOffer']['initialAmount']) && ($product['dailyDealOffer']['initialAmount'] > 0)): ?>
    <div class="cs-daily-deal-teaser__dd-detail cs-daily-deal-teaser__dd-detail--progress-bar">
        <p class="cs-daily-deal-teaser__dd-headline cs-daily-deal-teaser__dd-headline--limit"><?=__('Available items')?></p>

        <div class="cs-daily-deal-teaser__progress-bar">
            <div class="cs-cart-bonus__progress-wrapper cs-daily-deal-teaser__progress-bar-content">
                <?php 
                $percentage=(((int)$product['dailyDealOffer']['items'] / (int)$product['dailyDealOffer']['initialAmount']) * 100) / 100;
                $transforming=(1 - $percentage) / 2 / $percentage * 100
                ?>
                <div class="cs-daily-deal-teaser__progress-bg">
                    <div class="cs-daily-deal-teaser__progress-possible">
                        <div class="cs-cart-bonus__progress-done cs-daily-deal-teaser__progress" style="transform: scaleX(<?=$percentage?>) translateX(<?=-$transforming?>%)"></div>
                    </div>
                </div>
            </div>

            <span class="cs-daily-deal-teaser__available">
                <?=$product['dailyDealOffer']['items']?> / <?=$product['dailyDealOffer']['initialAmount']?>
            </span>
        </div>
    </div>
<?php endif; ?>

<div class="cs-daily-deal-teaser__dd-detail cs-daily-deal-teaser__dd-detail--countdown">
    <p class="cs-daily-deal-teaser__dd-headline cs-daily-deal-teaser__dd-headline--countdown"><?=__('Time left')?></p>

    <div class="cs-dailydeal cs-dailydeal--teaser">
        <div class="cs-dailydeal__countdown" data-dailydeal-end="<?=$product['dailyDealOffer']['to']?>"></div>
        <input type="hidden" name="cs-dailydeal__countdown-labels" class="cs-dailydeal__countdown-labels" value='<?=json_encode($labels)?>'>
    </div>
</div>


<?php if ($block->getVar('daily_deal_teaser/addtocart_button/show')): ?>
    <div class="cs-daily-deal-teaser__addtocart cs-addtocart">
        <?php
        $addToCartParameters = $viewModel->getAddToCartParameters($product['productObject']);
        $label = $productIsSimple ? __('Add to cart') : __('Configure');
        ?>
        <form data-role="tocart-form" action="<?= $addToCartParameters['action'] ?>" method="post">
            <input type="hidden" name="product" value="<?= $addToCartParameters['productId'] ?>">
            <input type="hidden" name="<?= $addToCartParameters['uencKey'] ?>" value="<?= $addToCartParameters['uencValue'] ?>">
            <?= $addToCartParameters['formKey'] ?>
            <button disabled type="submit" title="<?= $label ?>"
                    class="tocart | cs-button cs-button--type_grid-tocart">
                <span class="cs-button__span"><?= $label ?></span>
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl($block->getVar('daily_deal_teaser/addtocart_button/icon_path'))
                    ->setCssClass("cs-button__icon")
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
        </form>
    </div>
<?php endif; ?>