<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser */
/** @var $viewModel \MageSuite\ContentConstructorFrontend\Model\Component\DailyDealTeaser */

$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();
$jsSettings = json_encode($block->getVar('daily_deal_teaser/js') ?: '{}');
?>

<div class="cs-daily-deal-teaser__dd-detail cs-daily-deal-teaser__dd-detail--countdown">
    <p class="cs-daily-deal-teaser__dd-headline cs-daily-deal-teaser__dd-headline--countdown"><?=__('Time left')?></p>
    <!-- Data atrribute added until update to at least M2.3.4-p2 to fix translations-->
    <div class="cs-dailydeal cs-dailydeal--teaser"
        data-phrase-day="<?= __('Day') ?>"
        data-phrase-days="<?= __('Days') ?>"
        data-phrase-hour="<?= __('Hour') ?>"
        data-phrase-hours="<?= __('Hours') ?>"
        data-phrase-minute="<?= __('Min') ?>"
        data-phrase-minutes="<?= __('Min') ?>"
        data-phrase-second="<?= __('Sec') ?>"
        data-phrase-seconds="<?= __('Sec') ?>"
        data-mage-init='{ "ccDailyDealTeaser": <?= $jsSettings ?> }'
        >
        <div class="cs-dailydeal__countdown" data-dailydeal-end="<?=$product['dailyDealOffer']['to']?>"></div>
        <input type="hidden" name="cs-dailydeal__countdown-labels" class="cs-dailydeal__countdown-labels">
    </div>
</div>
