<?php
/** @var $block \MageSuite\ContentConstructorFrontend\Block\Component\DailyDealTeaser */
/** @var $viewModel \MageSuite\ContentConstructorFrontend\Model\Component\DailyDealTeaser */
$viewModel = $block->getViewModel();
$product = $viewModel->getProduct();
?>
<div class="cs-daily-deal-teaser__description-inner">
    <div class="cs-daily-deal-teaser__description-list">
        <?= $product['shortDescription']; ?>
    </div>
</div>
