<?php
$slide = $block->getSlide();
$slideIndex = $block->getSlideIndex();
$imageTeaserData = $block->getImageTeaser();

$isSlider = $block->getIsSlider();
$isSliderMobile = $block->getIsSliderMobile();
$contentPlacement = $block->getContentPlacement();
$contentAlign = $slide->getContentAlign();

/**
 * Call to action properties.
 */
$cta = $slide->getCta();
$ctaHref = $cta['href'] ?? '';

/**
 * Image properties with support for conditional lazy loading.
 */
$hasImage = !empty($slide->getSrc());
/**
 * Aspect ratio calculations preventing content jumping before images load.
 */
$slideImage = $slide->getImage();
$aspectRatio = isset($slideImage['aspect_ratio']) ? str_replace(':', '/', $slideImage['aspect_ratio']) : '';
/**
 * Contrast optimizers
 */
$contrastOptimizers = $slide->getOptimizers();

$colorScheme = $contrastOptimizers['color_scheme'] ?? null;
$mirrorImage = $contrastOptimizers['mirror_image'] ?? null;

$contrastOptimizersScenarios = $contrastOptimizers['scenarios'] ?? null;
$textShadow = $contrastOptimizersScenarios['text_shadow'] ?? null;
$container = $contrastOptimizersScenarios['container'] ?? null;
$openLinkInNewTab = $block->getOpenLinkInNewTab();

/**
 * Teaser content
 */

$slogan = $slide->getSlogan();
$description = $slide->getDescription();

/**
 * Video Teaser
 */
$videoTeaserData = $slide->getVideo();
$hasVideoTeaser = !empty($videoTeaserData['url']) && !empty($videoTeaserData['type']);

/**
 * Slide CSS classes
 */
$slideClasses = 'cs-image-teaser__slide cs-image-teaser__slide--scheme-'.$colorScheme;
if ($hasImage) {
    $slideClasses .= ' cs-image-teaser__slide--image-uploaded';
}
if ($hasVideoTeaser) {
    $slideClasses .= ' cs-image-teaser__slide--has-video-teaser';
}
$slideClasses .= ' '.$slide->getCcCssClasses();
?>
<li class="<?= $slideClasses ?>">
    <?= $this->getLayout()
        ->createBlock(\Magento\Framework\View\Element\Template::class)
        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/before_slide-wrapper.phtml')
        ->setImageTeaserData($imageTeaserData)
        ->setSlide($slide)
        ->setIsSlider($isSlider)
        ->setIsSliderMobile($isSliderMobile)
        ->setContentPlacement($contentPlacement)
        ->toHtml();
    ?>

    <?php if ($ctaHref): ?>
        <a href="<?= $block->escapeHtml($ctaHref) ?>" <?= $openLinkInNewTab ? 'target="_blank" rel="noopener noreferrer"' : ''?> class="cs-image-teaser__link">
    <?php endif; ?>
    <figure class="cs-image-teaser__figure">
        <?= $this->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/image.phtml')
            ->setImageTeaserData($imageTeaserData)
            ->setSlide($slide)
            ->setIsSlider($isSlider)
            ->setIsSliderMobile($isSliderMobile)
            ->setSlideIndex($slideIndex)
            ->setAspectRatio($aspectRatio)
            ->toHtml();
        ?>

        <?php if($slogan || $description || $ctaHref): ?>
            <figcaption class="cs-image-teaser__content-wrapper <?= isset($contentAlign['x']) ? 'cs-image-teaser__content-wrapper--content-align-x-' . $contentAlign['x'] : '';?> <?= isset($contentAlign['y']) ? ' cs-image-teaser__content-wrapper--content-align-y-' . $contentAlign['y'] : '';?> cs-image-teaser__content-wrapper--<?= $contentPlacement ?>">
                <?= $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/contrast_overlay.phtml')
                    ->setImageTeaserData($imageTeaserData)
                    ->setSlide($slide)
                    ->toHtml();
                ?>

                <?= $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/contrast_gradient.phtml')
                    ->setImageTeaserData($imageTeaserData)
                    ->setSlide($slide)
                    ->toHtml();
                ?>

                <?= $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/before_content.phtml')
                    ->setImageTeaserData($imageTeaserData)
                    ->setSlide($slide)
                    ->setIsSlider($isSlider)
                    ->setIsSliderMobile($isSliderMobile)
                    ->setContentPlacement($contentPlacement)
                    ->toHtml();
                ?>
                <div class="cs-image-teaser__content<?= isset($container['enabled']) && $container['enabled'] ? ' cs-image-teaser__content--container' : '' ?>">
                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/contrast_container.phtml')
                        ->setImageTeaserData($imageTeaserData)
                        ->setSlide($slide)
                        ->toHtml();
                    ?>
                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/before_text-content.phtml')
                        ->setImageTeaserData($imageTeaserData)
                        ->setSlide($slide)
                        ->setIsSlider($isSlider)
                        ->setIsSliderMobile($isSliderMobile)
                        ->setContentPlacement($contentPlacement)
                        ->toHtml();
                    ?>
                    <?php if($slogan || $description): ?>
                        <div class="cs-image-teaser__text-content<?= isset($textShadow['enabled']) && $textShadow['enabled'] ? ' cs-image-teaser__text-content--text-shadow cs-image-teaser__text-content--text-shadow-' . $textShadow['intensity'] : '' ?>">
                        <?php if($slogan): ?>
                            <?= $this->getLayout()
                                ->createBlock(\Magento\Framework\View\Element\Template::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/slogan.phtml')
                                ->setImageTeaserData($imageTeaserData)
                                ->setSlide($slide)
                                ->toHtml();
                            ?>
                        <?php endif; ?>
                        <?php if($description): ?>
                            <?= $this->getLayout()
                                ->createBlock(\Magento\Framework\View\Element\Template::class)
                                ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/description.phtml')
                                ->setImageTeaserData($imageTeaserData)
                                ->setSlide($slide)
                                ->toHtml();
                            ?>
                        <?php endif; ?>
                        </div>
                    <?php endif; ?>
                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/after_text-content.phtml')
                        ->setImageTeaserData($imageTeaserData)
                        ->setSlide($slide)
                        ->setIsSlider($isSlider)
                        ->setIsSliderMobile($isSliderMobile)
                        ->setContentPlacement($contentPlacement)
                        ->toHtml();
                    ?>
                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/cta.phtml')
                        ->setImageTeaserData($imageTeaserData)
                        ->setSlide($slide)
                        ->toHtml();
                    ?>
                </div>
                <?= $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/after_content.phtml')
                    ->setImageTeaserData($imageTeaserData)
                    ->setSlide($slide)
                    ->setIsSlider($isSlider)
                    ->setIsSliderMobile($isSliderMobile)
                    ->setContentPlacement($contentPlacement)
                    ->toHtml();
                ?>
            </figcaption>
        <?php endif; ?>
    </figure>
    <?php if ($ctaHref): ?>
        </a>
    <?php endif; ?>

    <?= $this->getLayout()
        ->createBlock(\Magento\Framework\View\Element\Template::class)
        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/after_slide-wrapper.phtml')
        ->setImageTeaserData($imageTeaserData)
        ->setSlide($slide)
        ->setIsSlider($isSlider)
        ->setIsSliderMobile($isSliderMobile)
        ->setContentPlacement($contentPlacement)
        ->toHtml();
    ?>
</li>
