<?php
$slide = $block->getSlide();
$imageTeaserData = $block->getImageTeaser();

$isSlider = $block->getIsSlider();
$isSliderMobile = $block->getIsSliderMobile();
$contentPlacement = $block->getContentPlacement();
$contentAlign = $slide->getContentAlign();

/**
 * Call to action properties.
 */
$cta = $slide->getCta();
$ctaHref = $cta['href'] ?? '';

/**
 * Image properties with support for conditional lazy loading.
 */
$hasImage = !empty($slide->getSrc());
/**
 * Aspect ratio calculations preventing content jumping before images load.
 */
$slideImage = $slide->getImage();
$aspectRatio = isset($slideImage['aspect_ratio']) ? explode(':', $slideImage['aspect_ratio']) : [];
$aspectRatioPadding = 0;
if (count($aspectRatio) === 2) {
    $aspectRatioPadding = ($aspectRatio[1] / $aspectRatio[0]) * 100;
}
/**
 * Contrast optimizers
 */
$contrastOptimizers = $slide->getOptimizers();

$colorScheme = $contrastOptimizers['color_scheme'];
$mirrorImage = $contrastOptimizers['mirror_image'];

$contrastOptimizersScenarios = $contrastOptimizers['scenarios'];
$textShadow = $contrastOptimizersScenarios['text_shadow'] ?? null;
$container = $contrastOptimizersScenarios['container'] ?? null;

?>
<li class="cs-image-teaser__slide cs-image-teaser__slide--scheme-<?= $colorScheme ?><?= $hasImage ? ' cs-image-teaser__slide--image-uploaded' : '' ?> <?= $slide->getCcCssClasses() ?>">
    
    <?= $this->getLayout()
        ->createBlock(\Magento\Framework\View\Element\Template::class)
        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/aspect_ratio_text-over-image.phtml')
        ->setImageTeaserData($imageTeaserData)
        ->setSlide($slide)
        ->setContentPlacement($contentPlacement)
        ->toHtml(); 
    ?>

    <?= $this->getLayout()
        ->createBlock(\Magento\Framework\View\Element\Template::class)
        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/before_slide-wrapper.phtml')
        ->setImageTeaserData($imageTeaserData)
        ->setSlide($slide)
        ->setIsSlider($isSlider)
        ->setIsSliderMobile($isSliderMobile)
        ->setContentPlacement($contentPlacement)
        ->toHtml(); 
    ?>

    <?php if ($ctaHref): ?>
        <a href="<?= $ctaHref ?>" class="cs-image-teaser__slide-wrapper">
    <?php else: ?>
        <div class="cs-image-teaser__slide-wrapper">
    <?php endif; ?>

        <?= $this->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/aspect_ratio_text-under-image.phtml')
            ->setImageTeaserData($imageTeaserData)
            ->setSlide($slide)
            ->setContentPlacement($contentPlacement)
            ->toHtml(); 
        ?>

        <?= $this->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/image.phtml')
            ->setImageTeaserData($imageTeaserData)
            ->setSlide($slide)
            ->setIsSlider($isSlider)
            ->setIsSliderMobile($isSliderMobile)
            ->toHtml(); 
        ?>

        <?= $this->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/contrast_overlay.phtml')
            ->setImageTeaserData($imageTeaserData)
            ->setSlide($slide)
            ->toHtml(); 
        ?>

        <?= $this->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/contrast_gradient.phtml')
            ->setImageTeaserData($imageTeaserData)
            ->setSlide($slide)
            ->toHtml(); 
        ?>

        <?= $this->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/before_content-wrapper.phtml')
            ->setImageTeaserData($imageTeaserData)
            ->setSlide($slide)
            ->setIsSlider($isSlider)
            ->setIsSliderMobile($isSliderMobile)
            ->setContentPlacement($contentPlacement)
            ->toHtml(); 
        ?>

        <div class="cs-image-teaser__content-wrapper cs-image-teaser__content-wrapper--content-align-x-<?= $contentAlign['x'] ?> cs-image-teaser__content-wrapper--content-align-y-<?= $contentAlign['y'] ?>"
            <?php if ($aspectRatio and $contentPlacement == 'under'): ?>
                style="margin-top: -<?= $aspectRatioPadding ?>%; padding-top: <?= $aspectRatioPadding ?>%"
            <?php endif; ?>
        >

            <?= $this->getLayout()
                ->createBlock(\Magento\Framework\View\Element\Template::class)
                ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/before_content.phtml')
                ->setImageTeaserData($imageTeaserData)
                ->setSlide($slide)
                ->setIsSlider($isSlider)
                ->setIsSliderMobile($isSliderMobile)
                ->setContentPlacement($contentPlacement)
                ->toHtml(); 
            ?>

            <div class="cs-image-teaser__content<?= isset($container['enabled']) && $container['enabled'] ? ' cs-image-teaser__content--container' : '' ?>">

                <?= $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/contrast_container.phtml')
                    ->setImageTeaserData($imageTeaserData)
                    ->setSlide($slide)
                    ->toHtml(); 
                ?>

                <?= $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/before_text-content.phtml')
                    ->setImageTeaserData($imageTeaserData)
                    ->setSlide($slide)
                    ->setIsSlider($isSlider)
                    ->setIsSliderMobile($isSliderMobile)
                    ->setContentPlacement($contentPlacement)
                    ->toHtml(); 
                ?>
                
                <div class="cs-image-teaser__text-content<?= isset($textShadow['enabled']) && $textShadow['enabled'] ? ' cs-image-teaser__text-content--text-shadow cs-image-teaser__text-content--text-shadow-' . $textShadow['intensity'] : '' ?>">
                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/slogan.phtml')
                        ->setImageTeaserData($imageTeaserData)
                        ->setSlide($slide)
                        ->toHtml(); 
                    ?>
                    <?= $this->getLayout()
                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/description.phtml')
                        ->setImageTeaserData($imageTeaserData)
                        ->setSlide($slide)
                        ->toHtml(); 
                    ?>
                </div>

                <?= $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/after_text-content.phtml')
                    ->setImageTeaserData($imageTeaserData)
                    ->setSlide($slide)
                    ->setIsSlider($isSlider)
                    ->setIsSliderMobile($isSliderMobile)
                    ->setContentPlacement($contentPlacement)
                    ->toHtml(); 
                ?>
                
                <?= $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/cta.phtml')
                    ->setImageTeaserData($imageTeaserData)
                    ->setSlide($slide)
                    ->toHtml(); 
                ?>
            </div>

            <?= $this->getLayout()
                ->createBlock(\Magento\Framework\View\Element\Template::class)
                ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/after_content.phtml')
                ->setImageTeaserData($imageTeaserData)
                ->setSlide($slide)
                ->setIsSlider($isSlider)
                ->setIsSliderMobile($isSliderMobile)
                ->setContentPlacement($contentPlacement)
                ->toHtml(); 
            ?>
        </div>

        <?= $this->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/after_content-wrapper.phtml')
            ->setImageTeaserData($imageTeaserData)
            ->setSlide($slide)
            ->setIsSlider($isSlider)
            ->setIsSliderMobile($isSliderMobile)
            ->setContentPlacement($contentPlacement)
            ->toHtml(); 
        ?>
    <?php if ($ctaHref): ?>
        </a>
    <?php else: ?>
        </div>
    <?php endif; ?>

    <?= $this->getLayout()
        ->createBlock(\Magento\Framework\View\Element\Template::class)
        ->setTemplate('MageSuite_ContentConstructorFrontend::component/image_teaser/slide_elements/hotspots/after_slide-wrapper.phtml')
        ->setImageTeaserData($imageTeaserData)
        ->setSlide($slide)
        ->setIsSlider($isSlider)
        ->setIsSliderMobile($isSliderMobile)
        ->setContentPlacement($contentPlacement)
        ->toHtml(); 
    ?>
</li>
