<?php
/** @var $viewModel \MageSuite\ContentConstructorFrontend\ViewModel\CmsPreloadImage */
$viewModel = $block->getViewModel();
$imageWidth = $block->getImageWidth();
$preloadImage = $viewModel->getPreloadImage($imageWidth);
$preloadImageSrcSet = $viewModel->getPreloadImageSrcSet($imageWidth);
?>
<?php if ($preloadImage && $preloadImageSrcSet): ?>
    <link rel="preload" href="<?= $preloadImage ;?>" imagesrcset="<?= $preloadImageSrcSet ;?>" as="image" importance="high">
<?php endif;?>
