<?php
$imageTeaserData = $block->getImageTeaserData();
?>

<button class="cs-image-teaser__nav cs-image-teaser__nav--prev cs-slider-navigation cs-slider-navigation--prev" disabled type="button">
    <?= $this->getLayout()
            ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
            ->setIconUrl($block->getIcon())
            ->setCssClass('cs-slider-navigation__icon')
            ->setAltText(__('Previous slide(s)'))
            ->setInlined(true)
            ->setLazyLoaded(false)
            ->toHtml();
    ?>
</button>
