<?php
$imageTeaserData = $block->getImageTeaserData();
?>

<button class="cs-image-teaser__nav cs-image-teaser__nav--next" type="button">
    <?= $this->getLayout()
        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
        ->setIconUrl($block->getIcon())
        ->setCssClass('cs-image-teaser__nav-icon')
        ->setInlined(true)
        ->setLazyLoaded(false)
        ->toHtml(); 
    ?>
</button>
